Мы завершили изучать NumPy. Теперь переходим к библиотеке Pandas, которая расширяет возможности NumPy и предоставляет новые инструменты, которые позволяют обрабатывать и преобразовывать структурированные данные.

## Pandas

### Что такое Pandas и как её используют аналитики данных

**Pandas** — это библиотека, которая позволяет работать с табличными данными на Python. Если NumPy работает с многомерными массивами чисел, то Pandas добавляет к этому метаданные. Например, названия столбцов, индексы строк, автоматическое выравнивание данных при операциях. Pandas умеет делать всё то же, что Excel, но быстрее, эффективнее, и с более мощным функционалом.

**Библиотека Pandas строится на двух основных типах объектов:**
1. **Pandas Series** — это одномерный вектор данных с индексом.
2. **Pandas DataFrame** — это двумерная таблица, которая состоит из нескольких Series.

Если продолжать аналогию с Excel, то DataFrame — это сама таблица, а Series — это отдельный столбец или строка из этой таблицы. DataFrame состоит из набора Series, которые объединяются общей индексацией. 

### Pandas Series

**Series** — это одномерный массив данных, который объединяет в себе два компонента: массив значений и массив индексом. Каждое значение в Series имеет соответствующую метку в индексе. Эта структура похожа на словарь Python, где ключи — это индексы, а значения — это данные. При этом Series сохраняет порядок элементов и поддерживает операции с векторами как в NumPy.

Внутри Series хранит данные в NumPy-массиве, поэтому все вычисления выполняются быстро. Индекс добавляет элементам семантический слой, то есть безымянный массив чисел становится полноценной структурой, где каждый элемент что-то означает.

**Создадим первую Series, а также укажем тип данных и имя объекта:**

In [5]:
import numpy as np
import pandas as pd

In [6]:
s = pd.Series([1, 2, 3], dtype=np.int32, name='numbers')
s

0    1
1    2
2    3
Name: numbers, dtype: int32

Мы создали Series из трёх целых чисел типа `int32`. Левая колонка показывает индекс — это `0, 1, 2`. Правая колонка содержит сами значения — это `1, 2, 3`. Внизу Pandas указывает имя Series, то есть `numbers`.

Параметр `dtype` контролирует тип данных в массиве. Pandas поддерживает все типы NumPy:
- `int8`;
- `int16`;
- `int32`;
- `int64`;
- `float32`;
- `float64`;
- `bool`;
- `object`. 

Явное указывать тип позволяет сэкономить память компьютера и ускорить вычисления. Например, `int8` занимает 1 байт вместо 8 байтов в `int64`, что критично, когда мы работаем с большими данными.

Параметр `name` задаёт имя самой серии — это метаданные объекта. Pandas использует `name`, чтобы идентифицировать структуру данных. Когда мы объединим несколько Series в DataFrame, это имя станет названием столбца. Мы можем использовать методы `s.describe()` и `s.info()`, чтобы вывести информацию о данных.

**Когда мы выводим Series, мы видим две колонки:**
1. **Индекс** — слева.
2. **Значения** — справа.

Это не делает объект двумерным. Series остаётся одномерным вектором, а индекс отображается для наглядности. Индекс — это метаданные. Его полезно использовать, когда нужно выровнять данные.

**Каждый элемент Series использует одновременно два индекса:**
1. **Именованный, или label-based** — работает как ключ в словаре.
2. **Целочисленный, или position-based** — работает как индекс в списке или массиве NumPy.

Если мы не указываем именованный индекс явно, Pandas автоматически создаёт его из целых чисел. Например, `0, 1, 2, ...`. Это делает Series похожей на словарь, так как у нас есть доступ по ключу, и на список, потому что у нас есть доступ по позиции. Если мы обратимся к несуществующему ключу, Pandas выдаст ошибку `KeyError`, как словарь, а если мы обратимся по некорректной позиции, то получим ошибку `IndexError`, как с списком. 

Такая комбинация подходов делает Series и DataFrame объектами со сложным устройством, которые, тем не менее, можно гибко использовать.

**Именованный индекс решает три ключевые задачи при анализе данных:**
1. **Идентифицирует данные.** Именованный индекс предоставляет метаданные для каждой строки, позволяет посмотреть результат в консоле, а также делает визуализацию понятнее.

    **Создадим Series с датами:**

In [7]:
dates = pd.Series([100, 150, 120], index=['2024-01-01', '2024-01-02', '2024-01-03'], name='sales')
dates

2024-01-01    100
2024-01-02    150
2024-01-03    120
Name: sales, dtype: int64

2. **Сопоставляет элементы по индексу.** При операциях между Series Pandas автоматически сопоставляет элементы по индексу, а не по позиции.
    
    **Создадим две Series с разными индексами:**

In [8]:
s1 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
s2 = pd.Series([10, 20, 30], index=['b', 'c', 'd'])
result = s1 + s2
result

a     NaN
b    12.0
c    23.0
d     NaN
dtype: float64

Pandas сопоставил только общие метки 'b' и 'c', где выполнил сложение: `2 + 10 = 12` и `3 + 20 = 23`. Для уникальных меток вернулось `NaN` — это специальное значение для отсутствующих данных. Это помогает предовратить ошибки, если данные не совпадают.

3. **Упрощает выборку данных.** Именованный индекс позволяет интуитивно получать подмножества данных по меткам.

    **Создадим Series с городами:**

In [9]:
cities = pd.Series([12_000_000, 5_000_000, 1_200_000],
                    index=['Москва', 'Санкт-Петербург', 'Казань'],
                    name='population')
cities['Москва']

np.int64(12000000)

Мы обратились к населению Москвы по названию города, а не по позиции `0`.

Здесь можно привести аналогию с телефонным справочником. Вместо того, чтобы помнить, что номер друга находится на позиции `42`, мы находим его по имени. В базах данных это работает похожим образом, через первичные ключи. Хотя есть и отличия. Например, индексы Pandas не гарантируют уникальность и могут дублироваться.

**Создадим Series с произвольным буквенным индексом:**

In [10]:
s = pd.Series([1, 2, 3], dtype=np.int32, name='numbers', index=['a', 'b', 'c'])
s

a    1
b    2
c    3
Name: numbers, dtype: int32

Теперь именованный индекс полностью отличается от целочисленных позиций и скрывает их при выводе. Мы видим буквы `a, b, c` слева от значений `1, 2, 3`. Целочисленная индексация никуда не исчезла, мы всё ещё можем обращаться к элементам по позициям `0, 1, 2`, просто интерфейс показывает только именованный индекс.

**Чтобы обратиться к элементу по именованному индексу, нужно использовать квадратные скобки, как это делается в словарях:**

In [11]:
s['a']

np.int32(1)

Мы получили значение `1`, которое соответствует индексу `a`.

**Кроме того, мы можем добавить новый элемент, как в словарь:**

In [12]:
s['u'] = 6
s

a    1
b    2
c    3
u    6
Name: numbers, dtype: int32

Мы добавили элемент с индексом `u` и значением `6`. Series расширилась за счёт новой строки в конце. 

**Чтобы получить все метки именованного индекса, используем свойство `.index`:**

In [13]:
s.index

Index(['a', 'b', 'c', 'u'], dtype='str')

Pandas вернёт объект `Index`, который содержит все метки индекса в том порядке, в котором они идут в Series. Это полезно, когда нужно проверить структуру данных или использовать индекс для следующих операций.

### Pandas DataFrame

Мы разобрались с Series, то есть с одномерным объектом Pandas. Теперь изучим DataFrame, который работает по тем же принципам, но добавляет второе измерение.

**DataFrame** — это двумерный массив табличных данных, который является анлалогом матрицы NumPy, где каждый столбец представляет собой отдельную Series.

**DataFrame имеет две оси индексации:**
1. Строковый индекс, как в Series.
2. Колоночный индекс, то есть названия столбцов.

Оба индекса работают по тем же принципам двойной индексации, что мы изучили для Series.

**Создадим DataFrame из случайной NumPy-матрицы:**

In [14]:
# Генерируем матрицу 5x3 из случайных чисел
m = np.random.rand(5, 3)

 # Создаём DataFrame из матрицы m
df = pd.DataFrame(m)

# Выводим таблицу
df

,0,1,2
0,0.508213,0.606578,0.165346
1,0.549019,0.461261,0.330864
2,0.122546,0.124615,0.795166
3,0.586651,0.844585,0.029506
4,0.101863,0.489086,0.362852


Pandas автоматически создал строковый индекс `0, 1, 2, 3 4` и колоночный индекс `0, 1, 2` — оба на основе RangeIndex. Таблица выглядит непривычно, потому что числа в заголовках столбцов не имеют смысла.

**Зададим столбцам понятные имена с помощью параметра `columns`:**

In [15]:
# Генерируем новую матрицу 5x3
m = np.random.rand(5, 3)

# Создаём DataFrame с именами столбцов
df = pd.DataFrame(

    # Передаём матрицу как данные
    data=m,

     # Задаём имена столбцов
    columns=['first', 'second', 'third'])

# Выводим таблицу
df

,first,second,third
0,0.811214,0.963593,0.343927
1,0.767215,0.134352,0.796051
2,0.638758,0.865404,0.035513
3,0.474841,0.815136,0.404176
4,0.040215,0.534565,0.148116


Теперь у каждой колонки есть название — `first`, `second` и `third`.

**Добавим текстовый столбец с именами, чтобы каждая строчка соответствовала строковому индексу:**

In [16]:
# Добавляем столбец `name` с именами
df['name'] = ['Dima', 'Ivan', 'Nikolay', 'Dima', 'Pavel'] 

# Выводим таблицу на экран
df

,first,second,third,name
0,0.811214,0.963593,0.343927,Dima
1,0.767215,0.134352,0.796051,Ivan
2,0.638758,0.865404,0.035513,Nikolay
3,0.474841,0.815136,0.404176,Dima
4,0.040215,0.534565,0.148116,Pavel


Pandas добавил столбец `name` в конец таблицы, а столбцы содержат данные разных типов. Например, столбцы `first`, `second` и `third` хранят тип `float64`, а столбец `name` хранит тип `object1`, то есть строки. В этом заключается основное отличие DataFrame от матрицы NumPy. Матрица NumPy хранит данные только одного типа, а DataFrame допускает разные типы в разных столбцах.

Квадратные скобки в DataFrame работают по колоночному индексу. Это отличает DataFrame от Series, где скобки работают по строковому индексу.

**Получим доступ к столбцу:**

In [17]:
# Обращаемся к столбцу `second` по имени в колоночном индексе
df['second'] 

0    0.963593
1    0.134352
2    0.865404
3    0.815136
4    0.534565
Name: second, dtype: float64

Pandas вернул столбец `second` как объект Series — со строковым индексом `0, 1, 2, 3, 4` и именем `second`. Каждый столбец DataFrame — это Series с общим строковым индексом таблицы. Так DataFrame строится из набора Series.

Кроме способа выше, существует ещё один, который позволяет обратиться к столбцу — с помощью атрибута объекта `df`.

**Получим доступ к столбцу вторым способом:**

In [18]:
# Обращаемся к столбцу `second` через атрибут объекта `df`
df.second

0    0.963593
1    0.134352
2    0.865404
3    0.815136
4    0.534565
Name: second, dtype: float64

Результат такой же, как если бы мы выполнили `df[second]`, но между этими способами есть разница. Мы не сможем обратиться по атрибуту объекта, если имя столбца содержит пробел, начинается с цифры  совпадает с именем встроенного атрибута

Теперь выберём несколько столбцов. **Чтобы это сделать, передадим список имён в квадратных скобках:**

In [19]:
# Выбираем столбцы `name` и `second` в заданном порядке
df[['name', 'second']] 

,name,second
0,Dima,0.963593
1,Ivan,0.134352
2,Nikolay,0.865404
3,Dima,0.815136
4,Pavel,0.534565


Pandas вернул столбцы в том порядке, в котором мы указали их в списке — `name` стоит первым, хотя в исходном DataFrame он последний. Порядок в списке полностью соответствует порядку столбцов в результате.

Стоит отметить, что результат выборки df['name'] и df[['name']] выглядит похоже, но вывод будет разным.

**Используем функцию `type()`, чтобы показать разницу:**

In [20]:
# Проверяем тип одиночной выборки
type(df['name'])

pandas.Series

In [21]:
# Проверяем тип выборки списком
type(df[['name']])

pandas.DataFrame

Как мы видим, `df['name']` возвращает Series, а `df[['name']]` возвращает DataFrame.

**Разница проявляется, когда мы вызываем методы, которые есть у Series, но отсутствуют у DataFrame:**

In [22]:
# Вызываем метод unique() на Series
df['name'].unique()

<StringArray>
['Dima', 'Ivan', 'Nikolay', 'Pavel']
Length: 4, dtype: str

In [23]:
# Обращаемся к атрибуту DataFrame
df[['name']].unique

AttributeError: 'DataFrame' object has no attribute 'unique'

Метод `.unique()` возвращает массив уникальных значений и доступен только у Series. DataFrame его не поддерживает, потому что таблица содержит несколько столбцов и применять `.unique()`, когда мы не указываем конкретный столбец, не имеет смысла.

**Если мы обратимся к DataFrame через целое число в квадратных скобках, то получим ошибку:**

In [ ]:
df[0]

Дело в том, что Pandas ищет в колоночном индексе метку `0`, но не находит её, потому что наши стобцы называются `first`, `second`, `third` и `name`. В итоге мы получаем `KeyError`. Квадратные скобки с одним значением всегда работают по колоночному индексу, поэтому целое число `0` Pandas интепретирует как имя столбца, а не как позицию.

Вспомним срезы. Если передать в квадратные скобки срез через двоеточие, то DataFrame ведёт себя иначе.

**Выборка будет идти по строкам через целочисленную индексацию:**

In [24]:
# Берём строки с позиция 0 и 1 через срез
df[:2]

,first,second,third,name
0,0.811214,0.963593,0.343927,Dima
1,0.767215,0.134352,0.796051,Ivan


In [25]:
# Переворачиваем таблицу. Теперь строки идут от последней к первой
df[::-1]

,first,second,third,name
4,0.040215,0.534565,0.148116,Pavel
3,0.474841,0.815136,0.404176,Dima
2,0.638758,0.865404,0.035513,Nikolay
1,0.767215,0.134352,0.796051,Ivan
0,0.811214,0.963593,0.343927,Dima


Так, `df[:2]` возвращает DataFrame из первых двух строк — с позициями `0` и `1`. df[::-1] переворачивает таблицу. Строка с позицией `4` становится первой, а строка с позицией `0` — последней. Это поведение не следует из общей логики доступа по колоночному индексу и является неким артефактом Pandas, который нужно просто запомнить.

Для явного доступа к строкам и столбцам Pandas предоставляет методы `.loc[]` и `.iloc[]`, которые мы рассмотрим в следующих разделах.

Помимо Num-Py-матрицы, DataFrame удобно создавать из словаря.

**Ключи словаря становятся именами столбцов, а значения по ключам — данным столбцов**

In [26]:
# Создаём словарь с двумя ключами и задаём столбцем имён со столбцом возрастов
d = {'name': ['Dmitry', 'Alexey', 'Vladimir', 'Elena'],
     'age': [24, 25, 30, 40]}

# Создаём DataFrame из словаря `d`
pd.DataFrame(d)

,name,age
0,Dmitry,24
1,Alexey,25
2,Vladimir,30
3,Elena,40


Как мы видим, Pandas автоматически создал строковый индекс `0, 1, 2, 3`. Для всех строк в словаре должны совпадать, иначе Pandas выдаст `ValueError`.

Есть ещё один способ создать DataFrame.

**Мы можем создать список словарей, где каждый словарь поисывает одну строку:**

In [27]:
# Создаём список из трёх словарей, который включает три строки
mydict = [{'a': 1, 'b': 2, 'c': 3, 'd': 4},
          {'a': 100, 'b': 200, 'c': 300, 'd': 400},
          {'a': 1000, 'b': 2000, 'c': 3000, 'd': 4000}]

# Создаём DataFrame из списка словарей
pd.DataFrame(mydict)

,a,b,c,d
0,1,2,3,4
1,100,200,300,400
2,1000,2000,3000,4000


Pandas читает каждый словарь как одну строку, а ключи `a, b, c, d` становятся именами столбцов. Оба этих способа указывают на родство DataFrame и словаря Python.

**Выделим три основных признака сходства DataFrame и словаря:**
1. Доступ по именованному ключу.
2. Расширение через новый ключ.
3. Ошибка `KeyError`, если мы обращаемся к несуществующему ключу.

### Просмотр таблицы

Мы научились создавать DataFrame разными способами. Теперь разберёмся, как просматривать его содержимое и получать информацию о его структуре. По умолчанию Jupyter Notebook и Google Colab обрезают вывод больших таблиц.

**Посмотрим, как это работает:**

In [28]:
# Создаём DataFrame из 100 строк и смотрим на вывод
pd.DataFrame(np.random.rand(100, 2))

,0,1
0,0.012476,0.795539
1,0.196581,0.669934
2,0.971317,0.910807
3,0.640151,0.566357
4,0.019070,0.004555
...,...,...
95,0.449624,0.357016
96,0.150909,0.368996
97,0.352160,0.851874
98,0.825832,0.741218


Pandas показывает первые и последние пять строк, а середину скрывает. Это позволяет компьютеру на зависнуть, когда мы работаем с большими данными. На практике просматривать все строки таблицы вручную не нужно. Достаточно посмотреть на несколько строк, чтобы понять структуру таблицы и убедиться, что данные считались корректно.

**Чтобы просматривать строки, Pandas предоставляет три метода:**

In [29]:
# Берём первые 2 строки таблицы
df.head(2)

,first,second,third,name
0,0.811214,0.963593,0.343927,Dima
1,0.767215,0.134352,0.796051,Ivan


In [30]:
# Берём последние 2 строки таблицы
df.tail(2)

,first,second,third,name
3,0.474841,0.815136,0.404176,Dima
4,0.040215,0.534565,0.148116,Pavel


In [31]:
# Берём 2 случайные строки таблицы
df.sample(2)

,first,second,third,name
2,0.638758,0.865404,0.035513,Nikolay
4,0.040215,0.534565,0.148116,Pavel


Как мы видим, все три методы возвращают DataFrame. Метод `.head()` помогает проверить начало таблицы сразу после загрузки. Метод `.tail()` показывает конец таблицы. Метод `.sample()` возвращает случайные строки, что полезно, когда нам нужно получить рандомный срез данных, который не зависит от порядка строк.

**Чтобы получить строковый и колоночный индексы таблицы, Pandas предоставляет свойства `.index` и `.columns`:**

In [32]:
# Получаем строковый индекс таблицы
df.index

RangeIndex(start=0, stop=5, step=1)

In [33]:
# Получаем колоночный индекс таблицы
df.columns

Index(['first', 'second', 'third', 'name'], dtype='str')

Оба свойства возвращают объект `Index`. Это тот же тип, который мы видели у Series.

**Поэтому для него работают индексация и срезы:**

In [34]:
# Берём имя второго столбца по позиции
df.columns[1]

'second'

In [35]:
# Берём имена столбцов с позиции 1 до 3, но не включаем 3
df.columns[1:3]

Index(['second', 'third'], dtype='str')

**Чтобы узнать форму таблицы, Pandas предоставляет свойство `.shape`:**

In [36]:
# Получаем количество строк таблицы
df.shape[0]

5

In [37]:
# Получаем количество столбцов таблицы
df.shape[1]

4

Свойство `.shape` возвращает кортеж. Первый элемент кортежа — это количество строк, а второй — количетсво столбцов. Например, для таблицы из 5 строк и 4 столбцов `.shape` вернёт (5, 4).

**Чтобы узнать типы данных столбцов, Pandas предоставляет свойства `d.types` и `df.info()`:**

In [38]:
# Получаем тип данных каждого столбца в виде Series
df.dtypes

first     float64
second    float64
third     float64
name          str
dtype: object

In [39]:
# Выводим сводку по структуре таблицы
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   first   5 non-null      float64
 1   second  5 non-null      float64
 2   third   5 non-null      float64
 3   name    5 non-null      str    
dtypes: float64(3), str(1)
memory usage: 292.0 bytes


Свойства `d.types` возвращает объект Series, где индекс — это имена столбцов, а значения — их типы.

**Метод `.info()` выводит более подробную информацию о таблице:**
- имена столбцов;
- количество непустых значений, или Non-Null Count;
- тип данных каждого столбца;
- объём памяти, который занимает таблица.

Граница `Non-Null Count` показывает, в каких столбцах есть пропуски. Если значение меньше общего числа строк, значит, в столбце есть `NaN`.

Чтобы изменить тип данных столбца, Pandas предоставляет метод `.astype()`. Он меняет тип данных в столбцах, которые мы указываем.

**Кроме того, ему можно передать словарь, где ключи — это имена столбцов, а значения — новые типы:**

In [40]:
# Меняем тип столбца `first` на `float64` с `float32`
df = df.astype({'first': np.float32})

In [41]:
# Проверяем, что тип столбца `first` изменился
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   first   5 non-null      float32
 1   second  5 non-null      float64
 2   third   5 non-null      float64
 3   name    5 non-null      str    
dtypes: float32(1), float64(2), str(1)
memory usage: 272.0 bytes


Pandas вернул новый DataFrame с изменённым типом столбца `first`. Исходный объект не меняется, поэтому мы присваем результат обратно в `df`.

**Сравним объём памяти при разных типах:**

In [42]:
# Смотрим, сколько памяти занимает `float16`
df.astype({'first': np.float16}).info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   first   5 non-null      float16
 1   second  5 non-null      float64
 2   third   5 non-null      float64
 3   name    5 non-null      str    
dtypes: float16(1), float64(2), str(1)
memory usage: 262.0 bytes


Разница составила 10 байт. На малом объёме данных профит от смены типа незначительный, но на таблице из миллиона строк разница между `float64` и `float16` позволит сэкономить память в четыре раза.

**Чтобы получить двумерный NumPy-массив из DataFrame, используем метод `.to_numpy()`:**

In [43]:
# Получаем NumPy-массив и берём все строки первых двух столбцов
df.to_numpy()[:, :2]

array([[0.8112144470214844, 0.9635932261177103],
       [0.7672148942947388, 0.13435244855780926],
       [0.638757586479187, 0.8654036550575245],
       [0.47484132647514343, 0.8151359104963647],
       [0.04021524265408516, 0.5345652014050245]], dtype=object)

Pandas вернул данные без индекса и имён столбцов, а оставил только сами значения. Здесь возникает проблема, что столбец `name` хранит строки, а остальные столбцы хранят числа. NumPy не умеет хранить данные разных типов в одном массиве, поэтому приводит все значения к типу `object`. Это делает массив неподходящим для числовых вычислений NumPy. Именно поэтому мы берём только первые два числовых столбца через срез `[:, :2]`.

**Чтобы получить статистику по всем числовым столбцам, используем метод `.describe()`:**

In [44]:
# Получаем статистику по числовым столбцам
df.describe()

,first,second,third
count,5.000000,5.000000,5.000000
mean,0.546449,0.662610,0.345557
std,0.311753,0.335571,0.292187
min,0.040215,0.134352,0.035513
25%,0.474841,0.534565,0.148116
50%,0.638758,0.815136,0.343927
75%,0.767215,0.865404,0.404176
max,0.811214,0.963593,0.796051


В выводе мы получаем DataFrame, где строки — это статистики, а столбцы — это числовые столбцы исходной таблицы.

**Строки таблицы содержат:**
- `count` — количество непустых значений в столбце;
- `mean` — среднее арифметическое значение;
- `std` — стандартное отклонение;
- `min` — минимальное значение;
- `25%`, `50%`, `75%` — первый, второй и третий квартили;
- `max` — максимальное значение.

Квартили делят отсортированный столбец на четыре равные части, а 50% — это медиана, то есть половина значений лежит ниже этой отметки, а половина выше.

**Строковый и колоночный индексы DataFrame — это одна и та же структура `Index`, только по разным осям:**
- строковый — по оси `axis=0`;
- колоночный — по оси `axis=1`.

Мы можем транспонировать таблицу с помощью метода `.T`, который поменяет индексы местами. То есть строки станут столбцами, а столбцы строками.

**Для этого используем свойство `.T`:**

In [45]:
# Транспонируем таблицу
df.T

,0,1,2,3,4
first,0.811214,0.767215,0.638758,0.474841,0.040215
second,0.963593,0.134352,0.865404,0.815136,0.534565
third,0.343927,0.796051,0.035513,0.404176,0.148116
name,Dima,Ivan,Nikolay,Dima,Pavel


Pandas поменял строки и столбцы местами. Теперь бывший колоночный индекс `first`, `second`, `third` и `name` стал строковым индексом, а бывший строковый индекс `0, 1, 2, 3, 4` стал колоночным. Это наглядно показывает, что оба индекса — это один и тот же тип объекта. 

### Сортировки

Мы научились просматривать структуру DataFrame. Теперь изучим, как упорядочить данные в таблице. С этим нам поможет сортировка.

**Сортировка** — это процесс, который изменяет таблицы и помогает упорядочить их.

**Для начала изучим метод `.sort_values()`, который позволяет упорядочить строки таблицы по значениям столбца, который мы указали:** 

In [46]:
# Сортируем строки по столбцу `first` от большего к меньшему
df.sort_values('first', ascending=False)

,first,second,third,name
0,0.811214,0.963593,0.343927,Dima
1,0.767215,0.134352,0.796051,Ivan
2,0.638758,0.865404,0.035513,Nikolay
3,0.474841,0.815136,0.404176,Dima
4,0.040215,0.534565,0.148116,Pavel


Параметр `ascending=False` задаёт порядок сортировки — `False` по убыванию, а `True` — по возрастанию, по умолчанию. То есть Pandas переставил строки так, что значения в строке `first` идут от максимального к минимальному. 

При этом давайте обратим внимание на строковый индекс. Он сохранил исходные метки `0, 1, 2, 3, 4` и переместился вместо со строками. Строка, которая была под индексом `3`, теперь стоит последней, но индекс остался при ней. Индекс привязывается к данным строки, а не к её позиции в таблице.

**Теперь давайте узнаем, как отсортировать строки по нескольким столбцам:**

In [47]:
# Сортируем сначала по `first`, а затем по `second`
df.sort_values(['first', 'second'])

,first,second,third,name
4,0.040215,0.534565,0.148116,Pavel
3,0.474841,0.815136,0.404176,Dima
2,0.638758,0.865404,0.035513,Nikolay
1,0.767215,0.134352,0.796051,Ivan
0,0.811214,0.963593,0.343927,Dima


Pandas сначал упорядочит строки по столбцу `first`, а затем внутри групп с одинаковыми значениями `first` упорядочит по столбцу `second`. Так как все значения в столбце `first` уникальные, сортировка по второму столбцу `second` не влияет на итоговый порядок строк. То есть у нас нет групп с одинаковыми значениями `first`, внутри которых нужно было бы упорядочить по `second`.

Если бы в столбце `first` были одинаковые значения, например, две строки со значением `0.5`, тогда эти две строк расположились бы рядом, а их порядок между собой определился бы по столбцу `second`.

**Чтобы задать разный порядок для разных столбцов, передадим список значений в параметр `ascending`:**

In [48]:
# Сортируем сначала `first` по возрастанию, а потом `second` по убыванию
df.sort_values(['first', 'second'], ascending=[True, False])

,first,second,third,name
4,0.040215,0.534565,0.148116,Pavel
3,0.474841,0.815136,0.404176,Dima
2,0.638758,0.865404,0.035513,Nikolay
1,0.767215,0.134352,0.796051,Ivan
0,0.811214,0.963593,0.343927,Dima


Pandas отсортировал столбец `first` по возрастанию, а столбец `second` по убыванию. Длина списка в `ascending` должна совпадать с количеством столбцов в первом параметре.

**Чтобы отсортировать строки по индексу, используем метод `.sort_index()`:**

In [49]:
# Сортируем строки по строковому индексу — от большего к меньшему
df.sort_index(ascending=False)

,first,second,third,name
4,0.040215,0.534565,0.148116,Pavel
3,0.474841,0.815136,0.404176,Dima
2,0.638758,0.865404,0.035513,Nikolay
1,0.767215,0.134352,0.796051,Ivan
0,0.811214,0.963593,0.343927,Dima


Pandas расположил строки так, что индекс идёт в порядке `4, 3, 2, 1, 0`. Содержимое столбцов переместилось вместе со своими индексами. Этот метод полезно использовать, когда индекс содержит дать или другие упорядоченные значения. 

**Чтобы отсортировать столбцы, используем параметр `axis`, который переключает направление сортировки с вертикального на горизонтальное:**

In [50]:
# Сортируем столбцы по именам в колоночном индексе от Z к A
df.sort_index(ascending=False, axis=1)

,third,second,name,first
0,0.343927,0.963593,Dima,0.811214
1,0.796051,0.134352,Ivan,0.767215
2,0.035513,0.865404,Nikolay,0.638758
3,0.404176,0.815136,Dima,0.474841
4,0.148116,0.534565,Pavel,0.040215


Pandas упорядочил столбцы по их именам в обратном алфавитном порядке: `third`, `second`, `name`, `first`. Здесь `axis=1` означает горизонтальную ось, то есть ось столбцов. Строки остались на своих местах, переставились только столбцы. По умолчанию `axis=0` работает с вертикальной осью, то есть с осью строк.

### Как использовать выборки и срезы

Мы научились сортировать данные в таблице. Теперь разберёмся, как выбирать нужные строки и столбцы. Pandas предоставляет несколько способ доступа к данным. У каждого есть свои особенности.

Сначала рассмотрим выборку через квадратные скобки. Мы уже видели, что квадратные скобки в DataFrame работают по-разному, в зависимости от того, что мы в них передаём. Давайте соберём все наши знания вместе.

**Если мы используем квадратные скобки с одним именем или списком имён, то мы выбираем столбцы по колоночному индексу:**

In [51]:
# Выбираем столбец `third` и получаем Series
df['third']

0    0.343927
1    0.796051
2    0.035513
3    0.404176
4    0.148116
Name: third, dtype: float64

In [52]:
# Выбираем столбцы `third` и `first` и получаем DataFrame
df[['third', 'first']]

,third,first
0,0.343927,0.811214
1,0.796051,0.767215
2,0.035513,0.638758
3,0.404176,0.474841
4,0.148116,0.040215


Первая ячейка возвращает Series, а вторая — DataFrame с двумя столбцами в указанном порядке.

При этом, если в квадратных скобках появляется срез, то поведение меняется.
**Выборка переключается на строки и использует целочисленные операции:**

In [53]:
# Берём строки с позиций `1, 2, 3` по целочисленному индексу
df[1:4]

,first,second,third,name
1,0.767215,0.134352,0.796051,Ivan
2,0.638758,0.865404,0.035513,Nikolay
3,0.474841,0.815136,0.404176,Dima


Pandas вернул три строки — со второй по четвёртую позицию, Правая граница `4` не включается, как в обычных списках Python.

Из-за этого возникает проблема. Как выбрать столбцы по целочисленным позициям? Как выбрать строки по именованному индексу? как сделать срез по столбцам? Квадратные скобки не дают такого контроля. **Для этого Pandas предоставляет методы `.loc[]` и `.iloc[]`.**

Метод `.loc[]` работает с именованными индексами для строк и столбцов.

**Сначала создадим строковый индекс с пятью буквами в алфавитном порядке место стандартного `0, 1, 2, 3, 4`:**

In [54]:
# Добавляем столбец для будущего индекса
df['new_index'] = pd.Series(['a', 'b', 'c', 'd', 'e'])

# Выводим таблицу с новым столбцом
df

,first,second,third,name,new_index
0,0.811214,0.963593,0.343927,Dima,a
1,0.767215,0.134352,0.796051,Ivan,b
2,0.638758,0.865404,0.035513,Nikolay,c
3,0.474841,0.815136,0.404176,Dima,d
4,0.040215,0.534565,0.148116,Pavel,e


**Теперь превратим столбец `new_index` в строковый индекс таблицы:**

In [55]:
# Делаем столбец `new_index` строковым индексом таблицы
df = df.set_index('new_index')

# Выводим таблицу с новым индексом
df

,first,second,third,name
new_index,,,,
a,0.811214,0.963593,0.343927,Dima
b,0.767215,0.134352,0.796051,Ivan
c,0.638758,0.865404,0.035513,Nikolay
d,0.474841,0.815136,0.404176,Dima
e,0.040215,0.534565,0.148116,Pavel


Метод `.set_index()` убрал столбец `new_index` из данных и сделал его индексом. Буквы `a, b, e, c, g` теперь стоят слева вместо чисел `0, 1, 2, 3, 4`.

**Теперь используем `.loc[]`, чтобы выбрать строку по её метке в индексе:**

In [56]:
# Выбираем строку с индексом `b` по именованной метке
df.loc['b']

first     0.767215
second    0.134352
third     0.796051
name          Ivan
Name: b, dtype: object

Pandas вернул строку `'b'` как Series, то есть все знчаения этой строки с именами столбцеов в качестве индекса.

Метод `.loc[]` использует квадратные скобки, хотя это метод. Разработчики Pandas выбрали такой синтаксис, чтобы он напоминал обычные срезы и выборки из списка массивов.

**Следовательно, метод `iloc[]` поддерживает срезы по именованному индексу:**

In [57]:
# Берём строки от индекса `b` до индекса `c` включительно
df.loc['b':'c']

,first,second,third,name
new_index,,,,
b,0.767215,0.134352,0.796051,Ivan
c,0.638758,0.865404,0.035513,Nikolay


Здесь есть важная особенность. Срез по именованном индексу включает обе границы — и левую, и правую. Обычные срезы Python включают только левую границу и исключают правую. Это нужно просто запомнить.

Мы также можем выбрать строки и столбцы одновременно.

**Метод `.loc[]` принимает два параметра через запятую: первый — для строк, а второй — для столбцов:**

In [58]:
# Берём строки от `b` до `c`, а также столбцы `second` и `third`
df.loc['b':'c', ['second', 'third']]

,second,third
new_index,,
b,0.134352,0.796051
c,0.865404,0.035513


Pandas вернул DataFrame из двух строк — `b` и `c`, а также двух столбцов — `second` и `third`. Первый параметр — срез строк, а  второй — список столбцов.

**Для столбцов можно также использовать срезы:**

In [59]:
# Берём все строки, а также столбцы от `name` до `first`
df.loc[:, 'name':'first']

""
new_index
a
b
c
d
e


Двоеточие без границ `:`, как мы знаем, означает "все элементы". Pandas вернул все строки и столбцы от `name` до `first` включительно по их порядку в колоночном индексе. Так как между `name` и `first` находилась только колонка `new_index`, Pandas вернул только её.

**Метод `.iloc[]` работает по тому же принципу, что и `.loc[]`, но использует целочисленные позиции вместо именованных меток:**

In [60]:
# Берём строки с позицией `1` и `2` по целочисленному индексу
df.iloc[1:3]

,first,second,third,name
new_index,,,,
b,0.767215,0.134352,0.796051,Ivan
c,0.638758,0.865404,0.035513,Nikolay


Pandas вернул строки с позиций `1` и `2` — это строки с индексами `b` и `c`. Правая граница среза `3` не включается, как в обычных Python-срезах.

**Метод `.iloc[]` также принимает два параметра — для строк и для столбцов:**

In [61]:
# Берём строки `0` и `2`, а также столбцы `0` и `2` по позициям
df.iloc[[0, 2], [0, 2]]

,first,third
new_index,,
a,0.811214,0.343927
c,0.638758,0.035513


Pandas вернул строки с позиций `0` и `2`, то есть индексы `a` и `e` и столбцы с позиций `0` и `2`, то есть столбцы `first` и `third`. Квадратные скобки `[[0, 2], [0, 2]] означают списки конкретных позиций, а не срезы.

### Чтение и запись данных

Мы научились выбирать данные из DataFrame разными способами. Теперь разберёмся, как загружать данные из файлов и сохранять результаты обратно на диск.

**Pandas поддерживает десятки форматов файлов:**
- CSV;
- Excel;
- JSON;
- SQL;
- Parquet;
- HDF5;
- и многие другие.

Для каждого формата есть функция `pd.read*()`, которая позволяет читать файлы, а также метод `.to_*()`, чтобы записывать файлы. Полный список форматов вы можете изучиь в [документации Pandas](https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html).

В этом разделе и далее мы будем работать с датасетом `iris.csv`. Вы можете скачать его из каталога с файлами к лекциям.

Самый распространённый формат табличным данных — это CSV, или Comma-Separated Values. Функция `pd.read_csv()` позволяет читать такие файлы и создавать DataFrame.

**Давайте проверим, как она работает:**

In [62]:
# Импортируем библиотеку, чтобы работать с данными
import pandas as pd

# Читаем CSV-файл и создаём DataFrame
iris = pd.read_csv('iris.csv')

# Выводим таблицу
iris

,sepal.length,sepal.width,petal.length,petal.width,variety
0,5.1,3.5,1.4,0.2,Setosa
1,4.9,3.0,1.4,0.2,Setosa
2,4.7,3.2,1.3,0.2,Setosa
3,4.6,3.1,1.5,0.2,Setosa
4,5.0,3.6,1.4,0.2,Setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Virginica
146,6.3,2.5,5.0,1.9,Virginica
147,6.5,3.0,5.2,2.0,Virginica
148,6.2,3.4,5.4,2.3,Virginica


Функция `pd.read_csv()` автоматически определила структуру файла — первая строка содержит имена столбцов, а значения разделяются запятыми. Pandas создал DataFrame, где первая строка файла стала колоночным индексом, а остальные строки — данными.  

**Функция `pd.read_csv()` предстваляет различные параметры, которые позволяют настроить чтение файла:**
- `sep` — задаёт разделитель столбцов, по умолчанию стоит запятая, но может быть точка с запятой и табуляция;
- `na_values` — указывает дополнительные значения, которые Pandas должен считать пропусками;
- `header` — указывает номер строки с именами столбцов, по умолчанию стоит `0`;
- `names` — задаёт имена столбцов вручную, если их нет в файле;
- `index_col` — указывает столбец, который нужно использовать строковый индекс.

**Например, если в файле вместо запятой используется точка с запятой, то нужно указать это в функции:**

In [63]:
# Читаем вымышленный CSV-файл c разделителем `;`
df = pd.read_csv('data.csv', sep=';')

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

Pandas предоставляет множество функций, которые позволяют читать файлы разных форматов. Давайте рассмотрим их с помощью автодополнения. Если вы работаете в IDE, то оно сработает автоматически, если в используете Jupyter Notebook, то нажмите `TAB`, чтобы появился список форматов:

In [ ]:
# Вводим начало имени функции, нажимаем `tab` и смотрим на список доступных форматов
pd.read_

**Pandas покажет список всех функций, например:**
- `read_csv`;
- `read_excel`;
- `read_json`;
- `read_sql`;
- `read_parquet`;
- `read_hdf`;
- `read_feather`;
- и многие другие.

Каждая функция работает с учётом особенностей своего формата.

**Чтобы сохранить DataFrame в CSV, нужно использовать метод `.to_csv()`:**

In [74]:
# Сохраняем таблицу в CSV без индекса
iris.to_csv('iris_test.csv', header=True, index=False)

# Выводим список файлов в текущей папке
!ls

ML_Lecture_01.ipynb  ML_Lecture_02.ipynb  iris.csv  iris_test.csv


Параметр `header=True` записывает имена столбцов как первую строку файла. Параметр `index=False` говорит Pandas не записывать строковый индекс как отдельный столбец, без этого параметра Pandas добавит безымянную колонку с индексами `0, 1, 2, ...`, что обычно не нужно.

Команда `!ls` в Linux или MacOS, а также `!dir` в Windows показывают файлы в текущем каталоге. Если вы выполнили ячейку выше, то в вашей директории появится новый каталог `iris_test.csv`. Это значит, что Pandas успешно сохранил данные.

### Фильтрация данных по условию

Мы научились загружать данные из файлов. Теперь разберёмся, как отбирать строки, которые удовлетворяют условиям, которые мы сами зададим. Этот механизм называется **фильтрацией** или **выборкой по маске**. Сначала изучим, что такое **булева маска**.

В NumPy булева маска — это массив, который состоит из значений `True` или `False`, где каждый элемент соответствует элементу исходного массива. В Pandas механизм похож, но работает иначе, то есть **маска — это Series из `True` и `False` с тем же индексом, что и у исходного DataFrame**. Pandas сопоставляет значения маски с данными по индексу, а не по позиции.


**Создадим булеву маску, которая проверяет условие для каждой строки:**

In [75]:
# Проверяем каждое значение столбца на условие больше 5
iris['sepal.length'] > 5.0

0       True
1      False
2      False
3      False
4      False
       ...  
145     True
146     True
147     True
148     True
149     True
Name: sepal.length, Length: 150, dtype: bool

Pandas вернул Series из `True` и `False` с тем же индексом, что у `iris`. Каждый элемент в Series показывает, выполняется ли условие для соответствующей строки. Если стоит `True`, то подходит, а если `False`, то нет.

**Теперь используем эту маску, чтобы отобрать строки, где условие вернуло `True`:**

In [76]:
# Отбираем строки, где условие вернуло `True`
iris[iris['sepal.length'] > 5.0]

,sepal.length,sepal.width,petal.length,petal.width,variety
0,5.1,3.5,1.4,0.2,Setosa
5,5.4,3.9,1.7,0.4,Setosa
10,5.4,3.7,1.5,0.2,Setosa
14,5.8,4.0,1.2,0.2,Setosa
15,5.7,4.4,1.5,0.4,Setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Virginica
146,6.3,2.5,5.0,1.9,Virginica
147,6.5,3.0,5.2,2.0,Virginica
148,6.2,3.4,5.4,2.3,Virginica


Pandas вернул DataFrame, который содержит только те строки, где sepal.length больше `5.0`. Строки с `False` в маске отбросились. 

В Pandas можно комбинировать несколько условий.

**Например, логические операторы `&`, `|` и `~` позволяют комбинировать условия, которые нужно заключать в круглые скобки:**

In [77]:
# Отбираем строки по двум условиям сразу 
iris[(iris['sepal.length'] > 5.0) & (iris['sepal.width'] <= 3.0)]

,sepal.length,sepal.width,petal.length,petal.width,variety
53,5.5,2.3,4.0,1.3,Versicolor
54,6.5,2.8,4.6,1.5,Versicolor
55,5.7,2.8,4.5,1.3,Versicolor
58,6.6,2.9,4.6,1.3,Versicolor
59,5.2,2.7,3.9,1.4,Versicolor
...,...,...,...,...,...
142,5.8,2.7,5.1,1.9,Virginica
145,6.7,3.0,5.2,2.3,Virginica
146,6.3,2.5,5.0,1.9,Virginica
147,6.5,3.0,5.2,2.0,Virginica


Оператор `&` возвращает `True` только там, где оба условия выполняются. Pandas отобрал строки, где длина Sepal больше 5.0 и ширина Sepal меньше или равна `3.0`.

Главная особенность масок Pandas заключается в том, что они привязаны к индексу, а не к позиции строк.

**Даже если мы отсортируем таблицу, маска всё равно отберёт правильные строки:**

In [78]:
# Сортируем таблицу и применяем ту же маску
iris.sort_values(['sepal.length', 'petal.length'])[(iris['sepal.length'] > 5.0) & (iris['sepal.width'] <= 3.0)]

/tmp/ipykernel_146/2318018107.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  iris.sort_values(['sepal.length', 'petal.length'])[(iris['sepal.length'] > 5.0) & (iris['sepal.width'] <= 3.0)]


,sepal.length,sepal.width,petal.length,petal.width,variety
98,5.1,2.5,3.0,1.1,Versicolor
59,5.2,2.7,3.9,1.4,Versicolor
84,5.4,3.0,4.5,1.5,Versicolor
81,5.5,2.4,3.7,1.0,Versicolor
80,5.5,2.4,3.8,1.1,Versicolor
...,...,...,...,...,...
130,7.4,2.8,6.1,1.9,Virginica
105,7.6,3.0,6.6,2.1,Virginica
135,7.7,3.0,6.1,2.3,Virginica
122,7.7,2.8,6.7,2.0,Virginica


Сначала Pandas отсортировал строки по `sepal.length` и `petal.length`, а затем применил маску, которая содержит индексы исходной таблицы. Поэтому Pandas правильно сопоставил `True` и `False` с нужными строками, несмотря на то, что порядок поменялся. Это позволяет защититься от ошибок, когда мы работаем с данными в разном порядке.

В Pandas можно отфильтровать строки по набору значений.

**Чтобы это сделать, нужно использовать метод `.isin()`, который проверяет, содержится ли значение в списке, который мы укажем:**

In [79]:
# Выбираем столбец `variety` с видами ирисов
iris['variety']

# Проверяем, входит ли значение в список двух видов
iris['variety'].isin(['Setosa', 'Virginica'])

0      True
1      True
2      True
3      True
4      True
       ... 
145    True
146    True
147    True
148    True
149    True
Name: variety, Length: 150, dtype: bool

Метод `.isin()` вернул булеву Series, где `True` стоит у строк с видом `Setosa` или `Virginica`, а `False` — для остальных.

**Ячейка с кодом выше эквивалентна этой ячейке:**

In [80]:
(iris['variety'] == 'Setosa') | (iris['variety'] == 'Virginica')

0      True
1      True
2      True
3      True
4      True
       ... 
145    True
146    True
147    True
148    True
149    True
Name: variety, Length: 150, dtype: bool

Но метод `.isin()` позволяет проверить, есть ли значение `variety` в списка `Setosa` и `Virginica` быстрее.

**Мы также можем применить эту маску для фильтрации:**

In [81]:
# Отбираем строки только видов `Setosa` и `Virginica`
iris[iris['variety'].isin(['Setosa', 'Virginica'])]

,sepal.length,sepal.width,petal.length,petal.width,variety
0,5.1,3.5,1.4,0.2,Setosa
1,4.9,3.0,1.4,0.2,Setosa
2,4.7,3.2,1.3,0.2,Setosa
3,4.6,3.1,1.5,0.2,Setosa
4,5.0,3.6,1.4,0.2,Setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Virginica
146,6.3,2.5,5.0,1.9,Virginica
147,6.5,3.0,5.2,2.0,Virginica
148,6.2,3.4,5.4,2.3,Virginica


Pandas вернул DataFrame без строк вида `Versicolor`. У нас остались только `Setosa` и `Virginica`.

### Вставка и изменение значений

Мы научились отбирать нужные строки по условиям. Теперь разберёмся, как менять значения в уже существующем DataFrame.

**В Pandas есть несколько способов, которые позволяют изменять данные. У каждого есть свои особенности:**
- `.loc[]` — изменяет элементы по именованным индексам и поддерживает изменение диапазонов;
- `.iloc[]` — изменяет элементы по целочисленным позициям, поддерживает изменение диапазонов;
- `.at[]` — изменяет один конкретный элемент по именованным индексам, работает быстрее для точечных изменений.

Методы `.loc[]` и `.iloc[]` универсальнее. Они позволяют изменить сразу несколько ячеек, а также целые строки и столбцы. При это размерность данных, которые мы вставляем, должна совпадать с размерностью диапазона, который мы выбрали.

**Давай узнаем, как изменить одно значение через `.iloc[]`. Для начала создадим новый DataFrame:**

In [82]:
# Создаём DataFrame из случайных чисел и генерируем матрицу 6x3
df = pd.DataFrame(np.random.rand(6, 3),
                  
                  # Задаём буквенный строковый индекс
                  index=['a', 'b', 'c', 'd', 'e', 'f'],
                  
                  # Задаём имена столбцов
                  columns=['first', 'second', 'third'])

# Выводим таблицу
df

,first,second,third
a,0.195827,0.721212,0.921017
b,0.554674,0.383036,0.135384
c,0.080195,0.809200,0.240434
d,0.521412,0.698284,0.935689
e,0.325485,0.439213,0.982092
f,0.771310,0.032001,0.406143


**Теперь изменим конкретное значение через `.iloc[]`:**

In [83]:
# Заменяем значение на пересечение строки b и стобца first
df.loc['b', 'first'] = 1.0

# Проверяем, что значение изменилось
df

,first,second,third
a,0.195827,0.721212,0.921017
b,1.000000,0.383036,0.135384
c,0.080195,0.809200,0.240434
d,0.521412,0.698284,0.935689
e,0.325485,0.439213,0.982092
f,0.771310,0.032001,0.406143


Pandas заменил слусайное число в строке `b` столбца `first` на `1.0`. Первый параметр `.iloc[]` указывает строку по её индексу, а второй — столбец по его имени. 

Теперь давайте разберёмся, как изменить одно значение через `.at[]`.

**Метод `.at[]` работает так же, как и `.iloc[]`, но его используют, чтобы изменять одну ячейку:**

In [84]:
# Заменяем значение на пересечение строки `e` и столбца `second`
df.at['e', 'second'] = 100

# Проверяем, что значение изменилось
df

,first,second,third
a,0.195827,0.721212,0.921017
b,1.000000,0.383036,0.135384
c,0.080195,0.809200,0.240434
d,0.521412,0.698284,0.935689
e,0.325485,100.000000,0.982092
f,0.771310,0.032001,0.406143


Pandas заменил значение в строке `e` столбца `second` на значение `100`. Метод `.at[]` работает быстрее, чем метод `.iloc[]`, потому что не проверяет, возможно ли изменить диапазон.

### Работа с пропущенными значениями

Мы научились изменять значения в DataFrame. Теперь разберёмся с особым типом значений — пропусками. Пропущенные данные встречаются почти в любом датасете, и в Pandas есть инструменты, которые позволяют их обрабатывать. 

Пропущенное значение — это отсутствие данных в ячейке таблицы. Pandas обозначает пропуски двумя способами:
- `np.nan`, или `NaN` — для числовых столбцов;
- `None` — для нечисловых типов данных.

По умолчанию пропуски не участвуют в вычислениях. Например, сумма столбца с пропуском игнорирует эти ячейки, а среднее считается тоьлко по непустым значениям.

**Создадим несколько пропусков в таблице:**

In [85]:
# Заменяем значение на пропуск в строке `e` столбца `second`
df.at['e', 'second'] = np.nan

# Заменяем значение на пропуск в строке `e` столбца `third`
df.at['e', 'third'] = np.nan

# Проверяем таблицу с пропусками
df

,first,second,third
a,0.195827,0.721212,0.921017
b,1.000000,0.383036,0.135384
c,0.080195,0.809200,0.240434
d,0.521412,0.698284,0.935689
e,0.325485,NaN,NaN
f,0.771310,0.032001,0.406143


Pandas показывает пропуски как `NaN` в ячейках. Строка `e` теперь содержит два пропуска.

**Чтобы найти пропуски в таблице, нужно использовать метод `.isna()`, который возвращает булеву маску, где `True` — это пропуск, а `False` — непустое значение:**

In [86]:
# Выводим булеву маску с пропусками для каждой ячейки
df.isna()

,first,second,third
a,False,False,False
b,False,False,False
c,False,False,False
d,False,False,False
e,False,True,True
f,False,False,False


Pandas вернул DataFrame той же формы, где `True` находится в позициях, где есть `NaN`.

**Чтобы посчитать общее количество пропусков, применим `.sum()` дважды:**

In [87]:
df.isna().sum().sum()

np.int64(2)

Первый `.sum()` считает пропуски в каждом столбце, а второй `.sum()` складывает эти числа. В результате мы получаем целое число пропусков по всей таблице.

**Мы также можем использовать метод `.info()`, чтобы узнать информацию о пропусках:**

In [88]:
# Выводим информацию по структуре таблицы с кол-вом непустых значений
df.info()

<class 'pandas.DataFrame'>
Index: 6 entries, a to f
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   first   6 non-null      float64
 1   second  5 non-null      float64
 2   third   5 non-null      float64
dtypes: float64(3)
memory usage: 364.0+ bytes


Колонка `Non-Null Count` показывает кол-во заполненных значений в каждом столбце. Если это число меньше общего количества строк, в столбце есть пропуски.

**Чтобы удалить строки с пропусками, используем метод `.dropna()`, который удаляет строки, если они содержат хотя бы один пропуск:**

In [89]:
# Выводим таблицу с пропусками
df

# Удаляем строки, где есть хотя бы один `NaN`
df = df.dropna()

# Проверяем таблицу
df

,first,second,third
a,0.195827,0.721212,0.921017
b,1.000000,0.383036,0.135384
c,0.080195,0.809200,0.240434
d,0.521412,0.698284,0.935689
f,0.771310,0.032001,0.406143


Мы получили DataFrame без строки `e`. Pandas не модифицирует данные без явного указания, поэтому нам понадобилось присвоить DataFrame обратно, чтобы сохранить результат.

**Чтобы удалить столбцы с пропусками, используем параметр `axis=1`, он позволяет переключить удаление со строк на столбцы:**

In [90]:
# Заменяем значение на пропуск в строке `f` столбца `second`
df.at['f', 'second'] = np.nan

# Заменяем значение на пропуск в строке `f` столбца `third`
df.at['f', 'third'] = np.nan

# Проверяем таблицу с пропусками
df

,first,second,third
a,0.195827,0.721212,0.921017
b,1.000000,0.383036,0.135384
c,0.080195,0.809200,0.240434
d,0.521412,0.698284,0.935689
f,0.771310,NaN,NaN


In [91]:
# Удаляем столбцы, где есть хотя бы один `NaN`
df.dropna(axis=1)

,first
a,0.195827
b,1.000000
c,0.080195
d,0.521412
f,0.771310


Pandas удалил столбцы `second` и `third`, потому что они содержат пропуски. У нас остался только один столбец `first` без пропусков.

**В качестве альтернативного способа мы можем транспонировать таблицу, удалить строки и транспонировать обратно:**

In [92]:
# Транспонируем таблицу, удаляем строки-столбцы, транспонируем обратно
df.T.dropna().T

,first
a,0.195827
b,1.000000
c,0.080195
d,0.521412
f,0.771310


Результат будет таким же, но код чуть сложнее.

**Чтобы заполнить пропуски одним значением, используем метод `.fillna()`:**

In [93]:
# Заменяем значение на пропуск в строке `a` столбца `first`
df.at['a', 'first'] = np.nan

# Выводим таблицу
df

,first,second,third
a,NaN,0.721212,0.921017
b,1.000000,0.383036,0.135384
c,0.080195,0.809200,0.240434
d,0.521412,0.698284,0.935689
f,0.771310,NaN,NaN


In [94]:
# Заполняем все NaN нулями
df = df.fillna(0)
df

,first,second,third
a,0.000000,0.721212,0.921017
b,1.000000,0.383036,0.135384
c,0.080195,0.809200,0.240434
d,0.521412,0.698284,0.935689
f,0.771310,0.000000,0.000000


Pandas заменил все `NaN` на `0`. Строка `f` теперь содержит нули в столбцах `second`, `third` и `first`.

**Чтобы заполнить каждый столбец своим значением, передадим словарь в `.fillna()`:**

In [95]:
# Заполняем `second` нулем, а `third` единицей
df = df.fillna({'second': 0, 'third': 1.0})
df

,first,second,third
a,0.000000,0.721212,0.921017
b,1.000000,0.383036,0.135384
c,0.080195,0.809200,0.240434
d,0.521412,0.698284,0.935689
f,0.771310,0.000000,0.000000


Pandas заменил пропуски в столбце `second` на `0`, а в столбце `third` на `1.0`. Столбцы, которые мы не указываем в словаре, остались без изменений.

**Теперь изучим несколько продвинутых методов для заполнения. Для начала создадим несколько пропусков:**

In [96]:
# Добавляем пропуск в строке `d` столбца `second`
df.at['d', 'second'] = np.nan

# Добавляем пропуск в строке `d` столбца `third`
df.at['d', 'third'] = np.nan

# Выводим таблицу
df

,first,second,third
a,0.000000,0.721212,0.921017
b,1.000000,0.383036,0.135384
c,0.080195,0.809200,0.240434
d,0.521412,NaN,NaN
f,0.771310,0.000000,0.000000


Теперь в таблице две строки с пропусками — `'d'` и `'e'`.

**Используем метод `bfill`, который заполняет пропуски, проходя с конца с таблицы к началу:**

In [97]:
# Заполняем пропуски значениями из следующих строк снизу вверх
df.bfill()

,first,second,third
a,0.000000,0.721212,0.921017
b,1.000000,0.383036,0.135384
c,0.080195,0.809200,0.240434
d,0.521412,0.000000,0.000000
f,0.771310,0.000000,0.000000


Pandas прошёл по каждому столбце снизу вверх и заменил каждый `NaN` на первое заполненное значение ниже.

**Метод `ffill` работает в обратном направлении, то есть с начала таблицы к концу:**

In [98]:
# Заполняем пропуски значениями из предыдущих строк сверху вниз
df.ffill()

,first,second,third
a,0.000000,0.721212,0.921017
b,1.000000,0.383036,0.135384
c,0.080195,0.809200,0.240434
d,0.521412,0.809200,0.240434
f,0.771310,0.000000,0.000000


Pandas прошёл по каждому столбцу сверху вниз и заменил каждый `NaN` на последнее непустое значение выше. Строка `d` получила значения из строки `c`, а строка `e` из строки `c`, потому что `d` тоже содержит пропуски.

Методы `bfill` и `ffill` используют для временных рядов. Например, если измерение пропущено в момент времени `t`, то обычно его заполняют значением из ближайшего момента времени.

### Статистические методы

Мы научились работать с пропущенными значениями. Теперь разберёмся, как вычислять статистики по данным.

**Чтобы вычислить среднее арифметическое для каждого числового столбца, нужно использовать метод `.mean()`:**

In [99]:
# Считаем среднее значение по каждому столбцу
df.mean()

first     0.474584
second    0.478362
third     0.324209
dtype: float64

Pandas вернул Series, где индекс — это имена столбцов, а значения — средние по этим столбцам. По умолчанию метод работает по оси `axis=0`, то есть по вертикали, он агрегирует строки в каждом столбце.

**Чтобы посчитать среднее только для одного столбца, нужно обратиться к нему напрямую:**

In [100]:
# Считаем средене значение только для столбца first
df['first'].mean()

np.float64(0.4745835556942266)

Pandas вернул одно число — среднее арифметическое всех значений столбца `first`.

**Чтобы посчитать стандартное отклонение, или меру разброса данных относительно среднего, нужно использовать метод `.std()`:**

In [101]:
# Считаем стандартное отклонение для каждого столбца
df.std()

first     0.432167
second    0.368034
third     0.409864
dtype: float64

Pandas вернул Series со стандартными отклонениями для каждого числового столбца. Чем больше значение, тем сильнее данные разбросаны относительно среднего.

**Чтобы посчитать дисперсию, или квадрат стандартного отклонения, нужно использовать метод `.var()`.**

In [102]:
# Считаем дисперсию для каждого столбца
df.var()

first     0.186768
second    0.135449
third     0.167988
dtype: float64

Pandas вернул Series с дисперсиями. Дисперсия показывает вариативность данных в квадратичной шкале. Связь со стандартным отклонением вычисляется так: `var = std²`.

**Чтобы посчитать количество уникальных значений в столбце, нужно использовать метод `.value_counts()`:**

In [103]:
# Считаем количество вхождения каждого уникального значения
iris['variety'].value_counts()

variety
Setosa        50
Versicolor    50
Virginica     50
Name: count, dtype: int64

Pandas вернул Series, где индекс — это уникальные значения столбца `variety`, то есть названия видов ирисов, а значения — количество строк с каждым видом. Результат автоматически отсортирован по убыванию частоты. Этот метод работает только с отдельными столбцами Series, а не с целым DataFrame.

### Применение собственных функций к данным

Мы научились использовать встроенные статистические методы Pandas. Теперь разберёмся, как применятьь собственные функции к строкам или столбцам таблицы. Для этого мы будем использовать метод `.apply()`, который позволяет задвать любую логику обработки.

**Метод `.apply()` принимает два ключевых параметра:**
1. **Функцию** — она определяет, что делать с каждой строкой или столбцом.
2. **Параметр `axis`** — он указывает направление обработки: `axis=1` для строк и `axis=0` для столбцов. 

Функция получает на вход Series, то есть строку или столбец, обрабатывает ее и возвращает результат через `return`. Pandas собирает все результаты обратно в DataFrame.

**Создадим функцию, которая изменяет значения в каждой строке:**

In [104]:
# Определяем функцию для обработки одной строки
def my_function(row):

    # Возводим значение столбца `first` в квадрат
    row['first'] = row['first'] ** 2

    # Вычитаем 1 из значения столбца `second`
    row['second'] = row['second'] - 1

    # Возвращаем изменённую строку
    return row

# Выводим сообщение о начале работы
print("begin")

# Применяем функцию к каждой строке таблицы
df.apply(my_function, axis=1)

begin


,first,second,third
a,0.000000,-0.278788,0.921017
b,1.000000,-0.616964,0.135384
c,0.006431,-0.190800,0.240434
d,0.271871,NaN,NaN
f,0.594919,-1.000000,0.000000


Параметр `axis=1` означает горизонтальную ось — ось столбцов. Pandas перебирает строки таблицы, передаёт каждую строку как Series в параметр `row` функции `my_function`, выполняет код функции и собирает результаты обратно в DataFrame. Внутри функции мы обращаемся к столбцам по именам: `row['first'], row['second']`.

**Теперь создадим функцию, которая обрабатывает столбцы:**

In [105]:
# Определяем функцию для обработки одного столбца
def my_function(column):

    # Проверяем имя столбца через атрибут `name`
    if column.name == 'first':

        # Возводим все значения столбца `first` в квадрат
        column = column ** 2

    # Проверяем, что это столбец `second`
    if column.name == 'second':

        # Вычитаем 1 из всех знчаений столбца `second`
        column = column - 1

    # Возвращаем изменённый столбец
    return column

# Выводим сообщение о начале работы
print("begin")

# Применяем функцию к каждому столбцу таблицы
df.apply(my_function, axis=0)

begin


,first,second,third
a,0.000000,-0.278788,0.921017
b,1.000000,-0.616964,0.135384
c,0.006431,-0.190800,0.240434
d,0.271871,NaN,NaN
f,0.594919,-1.000000,0.000000


Параметр `axis=0` означает вертикальную ось — ось строк. Pandas перебирает столбцы таблицы, передаёт каждый столбец как Series в параметр `column` функции `my_function`, выполняет код функции и собирает результаты обратно в DataFrame. Внутри функции мы проверяем имя столбца через атрибут `.name` — это свойство Series, которое хранит имя столбца из колоночного индекса.  

### Работа со строковыми данными

Мы научились применять собственные функции к данным. Теперь разберёмся, как обрабатывать текстовые столбцы. Pandas предоставляет векторизированные версии всех стандартных методов Python для строк через специальный асессор `.str`.

Асессор `.str` даёт доступ к строковым методам для всего столбца сразу. Если `s` — это Series с тесктовыми данными, то `s.str<метод>` применяет этот метод ко всем элементам столбца одновременно. Это работает быстрее, чем цикл или `.apply()`, потому что операции векторизованы. 

**Давайте добавим в таблицу новый столбец с текстовыми данными:**

In [106]:
# Создаём Series и присваиваем её как новый столбец
df['fourth'] = pd.Series(

    # Добавляем элементы
    ['Магистр по наукам о данных', 'Машинное обучение',
     'apply', 'дискретная математика', 'мы любим питон'],

    # Используем индекс из df для выравнивания
    index=df.index
)

# Выводим таблицу с новым столбцом
df

,first,second,third,fourth
a,0.000000,0.721212,0.921017,Магистр по наукам о данных
b,1.000000,0.383036,0.135384,Машинное обучение
c,0.080195,0.809200,0.240434,apply
d,0.521412,NaN,NaN,дискретная математика
f,0.771310,0.000000,0.000000,мы любим питон


Pandas добавил столбец `fourth` с текстовыми значениями. Параметр `index=df.index` гарантирует, что строки Series совпадают со строками DataFrame по индексу.

**Чтобы привести все символы строки к верхнему регистру, нужно использовать метод `.str.upper()`:**

In [107]:
# Переводим все строки столбца `fourth` в верхний регистр
df['fourth'].str.upper()

a    МАГИСТР ПО НАУКАМ О ДАННЫХ
b             МАШИННОЕ ОБУЧЕНИЕ
c                         APPLY
d         ДИСКРЕТНАЯ МАТЕМАТИКА
f                МЫ ЛЮБИМ ПИТОН
Name: fourth, dtype: str

Pandas вернул Series, где каждая строка преобразована в заглавные буквы. Исходный столбец остался без изменений.

**Чтобы разбить каждую строку на список подстрок по указанному разделителю, нужно использовать метод `.str.split():**

In [108]:
# Разбиваем каждую строку на список слов по пробелу
df['fourth'].str.split(' ')

a    [Магистр, по, наукам, о, данных]
b                [Машинное, обучение]
c                             [apply]
d            [дискретная, математика]
f                  [мы, любим, питон]
Name: fourth, dtype: object

Pandas вернул Series, где каждый элемент — это список слов. Например, строка `Машинное обучение` превратилась в список `['Машинное', 'обучение']`.

**Чтобы развернуть списки в отдельные строки, нужно использовать метод `.explode()`:**

In [109]:
# Разбиваем строки и разворачиваем списки в отдельные строки
df['fourth'].str.split(' ').explode()

a       Магистр
a            по
a        наукам
a             о
a        данных
b      Машинное
b      обучение
c         apply
d    дискретная
d    математика
f            мы
f         любим
f         питон
Name: fourth, dtype: str

Pandas создал новую Series, где каждое слово из списков стало отдельной строкой с тем же индексом, что и у исходной строки. Например, индекс `a` теперь соответствует нескольким строкам — по одной на каждое слово из фразы "Магистр по наукам о данных".

**Теперь узнаем, как создать DataFrame из разбитых строк. Для этого воспользуемся параметром `expand=True`, чтобы каждая часть строки попала в отдельный столбец:**

In [110]:
# Разбиваем строки и создаём Data Frame со столбцами для каждой части
df['fourth'].str.split(' ', expand=True)

,0,1,2,3,4
a,Магистр,по,наукам,о,данных
b,Машинное,обучение,NaN,NaN,NaN
c,apply,NaN,NaN,NaN,NaN
d,дискретная,математика,NaN,NaN,NaN
f,мы,любим,питон,NaN,NaN


Pandas создал DataFrame, где количество столбцов равно максимальному количеству слов в строках. Первое слово попало в столбец `0`, а второе в столбец `1`, и так далее. Если в строке меньше слов, чем столбцов, Pandas заполняет недостающие ячейки значением `NaN`.

**Кроме того, мы можем ограничить количество разбиений через второй параметр:**

In [111]:
# Разбиваем только по первому пробелу
df['fourth'].str.split(' ', n=1, expand=True)

,0,1
a,Магистр,по наукам о данных
b,Машинное,обучение
c,apply,NaN
d,дискретная,математика
f,мы,любим питон


Pandas создаёт DataFrame с двумя столбцами. Параметр `n=1` указывает на то, что нужно разбить строку максимум на две части: до первого пробела и после.

### Соединение таблиц

Мы научились работать со строковыми данными. Теперь разберёмся, как объединять несколько таблиц в одну. Pandas предоставляет три основных метода для соединения: `pd.concat()`, `pd.merge()` и `pd.join()`. Начнём с `pd.concat()`, который объединяет таблицы по осям. Для начала узнаем, что такое конкатенация.

**Конкатенция** — это соединение нескольких таблиц вдоль одной из осей. Метод `pd.concat()` принимает список DataFrame или Series и склеивает их либо вертикально, то есть добавляет строки, либо горизонтально, то есть добавляет столбцы.

**По умолчанию `pd.concat()` соединяет таблицы вертикально через `axis=0`:**

In [112]:
# Соединяем две копии таблицы iris по вертикали
vert_concat = pd.concat([iris, iris])

# Выводим результат
vert_concat

,sepal.length,sepal.width,petal.length,petal.width,variety
0,5.1,3.5,1.4,0.2,Setosa
1,4.9,3.0,1.4,0.2,Setosa
2,4.7,3.2,1.3,0.2,Setosa
3,4.6,3.1,1.5,0.2,Setosa
4,5.0,3.6,1.4,0.2,Setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Virginica
146,6.3,2.5,5.0,1.9,Virginica
147,6.5,3.0,5.2,2.0,Virginica
148,6.2,3.4,5.4,2.3,Virginica


Pandas добавил строки второй таблицы под строки первой таблицы. Индексы не сбросились — теперь каждый индекс встречается дважды. Например, индекс `0` соответствует и первой строке первой таблицы и первой строке второй таблицы.

**Дублирующиеся индексы могут вызвать неожиданные поведение при выборке:**

In [113]:
# Обращаемся к индексу 110
vert_concat.loc[110]

,sepal.length,sepal.width,petal.length,petal.width,variety
110,6.5,3.2,5.1,2.0,Virginica
110,6.5,3.2,5.1,2.0,Virginica


Pandas вернул обе строки с индексом `110` — одну из первой таблицы и ещё другую из второй. Это может мешать при работе с данными.

**Чтобы сбросить индекс после соединения таблиц, нужно использовать метод `.reset_index()`, который создаёт новый последовательный индекс `0, 1, 2, ...` и превращает старый индекс в обычный столбец:**

In [114]:
# Сбрасываем старый индекс и создаём новый последовательный
vert_concat.reset_index()

,index,sepal.length,sepal.width,petal.length,petal.width,variety
0,0,5.1,3.5,1.4,0.2,Setosa
1,1,4.9,3.0,1.4,0.2,Setosa
2,2,4.7,3.2,1.3,0.2,Setosa
3,3,4.6,3.1,1.5,0.2,Setosa
4,4,5.0,3.6,1.4,0.2,Setosa
...,...,...,...,...,...,...
295,145,6.7,3.0,5.2,2.3,Virginica
296,146,6.3,2.5,5.0,1.9,Virginica
297,147,6.5,3.0,5.2,2.0,Virginica
298,148,6.2,3.4,5.4,2.3,Virginica


Pandas создал новый столбец `index` со старыми значениями индекса и присвоил строкам новые индексы от `0` до `299`. Теперь каждый индекс уникален.

**Давайте проверим это:**

In [115]:
# Обращаемся к индексу 110
vert_concat.reset_index().loc[110]

index                 110
sepal.length          6.5
sepal.width           3.2
petal.length          5.1
petal.width           2.0
variety         Virginica
Name: 110, dtype: object

Pandas вернул одну строку, которая находится на позиции `110` в новом индексе.

**Кроме того, мы можем передать `ignore_index=True` сразу в `pd.concat()`:**

In [116]:
# Соединяем таблицы и сразу создаём новый индекс
pd.concat([iris, iris], ignore_index=True)

,sepal.length,sepal.width,petal.length,petal.width,variety
0,5.1,3.5,1.4,0.2,Setosa
1,4.9,3.0,1.4,0.2,Setosa
2,4.7,3.2,1.3,0.2,Setosa
3,4.6,3.1,1.5,0.2,Setosa
4,5.0,3.6,1.4,0.2,Setosa
...,...,...,...,...,...
295,6.7,3.0,5.2,2.3,Virginica
296,6.3,2.5,5.0,1.9,Virginica
297,6.5,3.0,5.2,2.0,Virginica
298,6.2,3.4,5.4,2.3,Virginica


Результат будет таким же, как если бы мы использовать `.reset_index()`, но код короче.

**Чтобы соединить таблицы горизонтально, нужно использовать параметр `axis=1`:**

In [117]:
# Соединяем две копии таблицы `iris` по горизонтали
hor_concat = pd.concat([iris, iris], axis=1)

# Получаем результат соединения
hor_concat

,sepal.length,sepal.width,petal.length,petal.width,variety,sepal.length,sepal.width,petal.length,petal.width,variety
0,5.1,3.5,1.4,0.2,Setosa,5.1,3.5,1.4,0.2,Setosa
1,4.9,3.0,1.4,0.2,Setosa,4.9,3.0,1.4,0.2,Setosa
2,4.7,3.2,1.3,0.2,Setosa,4.7,3.2,1.3,0.2,Setosa
3,4.6,3.1,1.5,0.2,Setosa,4.6,3.1,1.5,0.2,Setosa
4,5.0,3.6,1.4,0.2,Setosa,5.0,3.6,1.4,0.2,Setosa
...,...,...,...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Virginica,6.7,3.0,5.2,2.3,Virginica
146,6.3,2.5,5.0,1.9,Virginica,6.3,2.5,5.0,1.9,Virginica
147,6.5,3.0,5.2,2.0,Virginica,6.5,3.0,5.2,2.0,Virginica
148,6.2,3.4,5.4,2.3,Virginica,6.2,3.4,5.4,2.3,Virginica


 Pandas добавил столбцы второй таблицы справа от столбцов первой таблицы. Теперь в таблице два столбца `sepal.length`, два столбца `sepal.width` и так далее — по одному набору из каждой таблицы.

**Если мы обратимся к столбцу с дублирующимся именем, Pandas вернёт два столбца с таким именем:**

In [118]:
# Обращаемся к столбцу sepal.length
hor_concat['sepal.length']

,sepal.length,sepal.length
0,5.1,5.1
1,4.9,4.9
2,4.7,4.7
3,4.6,4.6
4,5.0,5.0
...,...,...
145,6.7,6.7
146,6.3,6.3
147,6.5,6.5
148,6.2,6.2


Как мы видим, Pandas вернул сразу два столбца.

**В Pandas есть параметр `join`, который контролирует, как обрабатываются строки или столбцы таблиц:**
- **`join='outer'`** объединяет все индексы из обеих таблиц и заполняет пустые значения `NaN`;
- **`join='inner'`** оставляет только общие индексы, которые есть в обоих таблицах.

**Проверим разницу на горизонтальном соединении:**

In [119]:
# Соединяем полную таблицу с первыми 50 строками через outer
pd.concat([iris, iris[:50]], join='outer', axis=1)

,sepal.length,sepal.width,petal.length,petal.width,variety,sepal.length,sepal.width,petal.length,petal.width,variety
0,5.1,3.5,1.4,0.2,Setosa,5.1,3.5,1.4,0.2,Setosa
1,4.9,3.0,1.4,0.2,Setosa,4.9,3.0,1.4,0.2,Setosa
2,4.7,3.2,1.3,0.2,Setosa,4.7,3.2,1.3,0.2,Setosa
3,4.6,3.1,1.5,0.2,Setosa,4.6,3.1,1.5,0.2,Setosa
4,5.0,3.6,1.4,0.2,Setosa,5.0,3.6,1.4,0.2,Setosa
...,...,...,...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Virginica,NaN,NaN,NaN,NaN,NaN
146,6.3,2.5,5.0,1.9,Virginica,NaN,NaN,NaN,NaN,NaN
147,6.5,3.0,5.2,2.0,Virginica,NaN,NaN,NaN,NaN,NaN
148,6.2,3.4,5.4,2.3,Virginica,NaN,NaN,NaN,NaN,NaN


Pandas вернул DataFrame со всеми `150` строками. Строки с индексами `50-149` существуют только в левой таблице, поэтому столбцы из правой таблицы `(iris[:50])` заполняются `NaN` для этих строк.

**Теперь используем `join='inner'`:**

In [120]:
# Соединяем полную таблицу с первыми 50 строками через inner
pd.concat([iris, iris[:50]], join='inner', axis=1)

,sepal.length,sepal.width,petal.length,petal.width,variety,sepal.length,sepal.width,petal.length,petal.width,variety
0,5.1,3.5,1.4,0.2,Setosa,5.1,3.5,1.4,0.2,Setosa
1,4.9,3.0,1.4,0.2,Setosa,4.9,3.0,1.4,0.2,Setosa
2,4.7,3.2,1.3,0.2,Setosa,4.7,3.2,1.3,0.2,Setosa
3,4.6,3.1,1.5,0.2,Setosa,4.6,3.1,1.5,0.2,Setosa
4,5.0,3.6,1.4,0.2,Setosa,5.0,3.6,1.4,0.2,Setosa
5,5.4,3.9,1.7,0.4,Setosa,5.4,3.9,1.7,0.4,Setosa
6,4.6,3.4,1.4,0.3,Setosa,4.6,3.4,1.4,0.3,Setosa
7,5.0,3.4,1.5,0.2,Setosa,5.0,3.4,1.5,0.2,Setosa
8,4.4,2.9,1.4,0.2,Setosa,4.4,2.9,1.4,0.2,Setosa
9,4.9,3.1,1.5,0.1,Setosa,4.9,3.1,1.5,0.1,Setosa


Pandas вернул DataFrame только с 50 строками, теми, которые есть в обеих таблицах. При этом строки с `50 по 149` отбросились, потому что их нет в правой таблице.

**Чтобы выполнить вертикальное соединение, нужно также использовать параметр `join`:**

In [121]:
# Соединяем полную таблицу с двумя столбцами через outer
pd.concat([iris, iris[['sepal.length', 'petal.length']]], join='outer', axis=0)

,sepal.length,sepal.width,petal.length,petal.width,variety
0,5.1,3.5,1.4,0.2,Setosa
1,4.9,3.0,1.4,0.2,Setosa
2,4.7,3.2,1.3,0.2,Setosa
3,4.6,3.1,1.5,0.2,Setosa
4,5.0,3.6,1.4,0.2,Setosa
...,...,...,...,...,...
145,6.7,NaN,5.2,NaN,NaN
146,6.3,NaN,5.0,NaN,NaN
147,6.5,NaN,5.2,NaN,NaN
148,6.2,NaN,5.4,NaN,NaN


Pandas вернул DataFrame со всеми таблицами. Столбцов `sepal.width` и `petal.width`, а также `variety` нет во второй таблице, поэтому для строк из второй таблицы эти столбцы заполняются `NaN`. 

**Теперь используем `join='inner'`:**

In [122]:
# Соединяем полную таблицу с двумя столбцами через inner
pd.concat([iris, iris[['sepal.length', 'petal.length']]], join='inner', axis=0)

,sepal.length,petal.length
0,5.1,1.4
1,4.9,1.4
2,4.7,1.3
3,4.6,1.5
4,5.0,1.4
...,...,...
145,6.7,5.2
146,6.3,5.0
147,6.5,5.2
148,6.2,5.4


Pandas верунл DataFrame только с двумя столбцами — `sepal.length` и `petal.length`, которые есть в обеих таблицах, а остальные столбцы отбросились.

### Метод `pd.merge()`

Мы научились склеивать таблицы через `pd.concat()`. Теперь разберёмся с более мощным методом — `pd.merge()`, который работает как `JOIN` в SQL и соединяет таблицы по совпадающим значениям в указанным столбцах или индексах.

**Pandas поддерживает четыре типа соединений:**
1. **Inner join, или внутреннее,** — оставляет только строки, где ключи совпадают в обоих таблицах.
2. **Left join, или левое,** — сохраняет все строки из левой таблицы, для строк без совпадений в правой таблице заполняет `NaN`.
3. **Right join, или правое,** — сохраняет все строки из правой таблицы, для строк без совпадений в левой таблице заполняет `NaN`.
4. **Outer join, или внешнее,** — сохраняет все строки из обеих таблиц, заполняет `NaN` для несовпадающих ключей.

Пересечение и объединение происходят в множестве ключей, то есть столбцов, по которым таблицы соединяются. Например, для `inner join` результат содержит только те комбинации строк, где значения ключевых столбцов совпадают в обеих таблицах.

**Давайте создадим две таблицы для демонстрации:**

In [123]:
df_left = pd.DataFrame({
    'name': ['Dmitry', 'Sergey', 'Anna'],
    'age': [20, 30, 40],
    'fav_col': ['red', 'blue', 'green']
}, index=['a', 'a', 'b'])

df_right = pd.DataFrame({
    'name': ['Dmitry', 'Sergey', 'Anna', 'Vasiliy'],
    'age': [20, 35, 40, 50],
    'second_name': ['Petrov', 'Ivanov', 'Smirnova', 'Alexandrov']
}, index=['a', 'b', 'c', 'b'])

df_left

,name,age,fav_col
a,Dmitry,20,red
a,Sergey,30,blue
b,Anna,40,green


In [124]:
df_right

,name,age,second_name
a,Dmitry,20,Petrov
b,Sergey,35,Ivanov
c,Anna,40,Smirnova
b,Vasiliy,50,Alexandrov


Обратим внимание, что в левой таблице три строки, а в правой четыре. Индексы содержит дубликаты. Имя `'Sergey'` есть в обеих таблицах, но с разными возрастом — `30` в левой таблице и `35` в правой. 

**В методе `pd.merge()` есть параметры, которые позволяют контролировать соединение таблиц:**
- `left`,`right` — левая и правая таблицы для соединения;
- `how` — тип соединения, например, `inner` выставляется по умолчанию, а также есть `outer`, `left` и `right`.

**Есть также и параметры для выбора ключей:**
- `left_index=True/False` — использовать индекс левой таблицы как ключ;
- `right_index=True/False` — использовать индекс правой таблицы как ключ;
- `left_on='column'` — использовать столбец из левой таблицы как ключ;
- `right_on='column'` — использовать столбец из правой таблицы как ключ;
- `on='column'` — если имена ключевых столбцов совпадают в обеих таблицах.

**Давайте рассмотрим примеры работы этих параметров:**

In [125]:
# Соединяем по индексам обеих таблиц
pd.merge(df_left, df_right, left_index=True, right_index=True)

,name_x,age_x,fav_col,name_y,age_y,second_name
a,Dmitry,20,red,Dmitry,20,Petrov
a,Sergey,30,blue,Dmitry,20,Petrov
b,Anna,40,green,Sergey,35,Ivanov
b,Anna,40,green,Vasiliy,50,Alexandrov


In [126]:
# Соединяем столбец name слева с second_name справа
pd.merge(df_left, df_right, left_on='name', right_on='second_name')

,name_x,age_x,fav_col,name_y,age_y,second_name


In [127]:
# Соединяем по столбцу name, который есть в обеих таблицах
pd.merge(df_left, df_right, on='name')

,name,age_x,fav_col,age_y,second_name
0,Dmitry,20,red,20,Petrov
1,Sergey,30,blue,35,Ivanov
2,Anna,40,green,40,Smirnova


**В Pandas есть параметр `validate`, который проверяет, соответствует ли результат ожидаемому типу связи между таблицами:**
- `one_to_one` или `1:1` — ключи уникальны в таблицах, каждой строке слева соответстует максимум одна строка справа;
- `one_to_many` или `1:m` — ключи уникальны в левой таблице, одной строке слева может соответствовать несколько строк справа;
- `many_to_one` или `m:1` — ключи уникальны в правой таблице, нескольким строкам слева может соответствовать одна строка справа;
- `many_to_many` или `m:m` — ключи неуникальны в обеих таблицах, проверки не происходят.

Если фактическая связь не соответствует указанной в `validate`, Pandas выдаёт ошибку `MergeError`. Это помогает обнаружить проблемы в данных на раннем этапе.

### Группировка данных

Мы научились соединять таблицы. Теперь разберёмся, как вычислять статистики по группам. Группировка в Pandas работает аналогично `GROUP BY` в SQL и позволяет разбить данные на подгруппы, вычислить агрегаты для каждой группы и собрать результаты обратно в таблицу.

**Чтобы сгруппировать данные и посчитать среднее, нужно использовать метод `.groupby()`, который разбивает таблицы на группы по уникальным значениям столбца, который мы указываем:**

In [128]:
# Группируем по столбцу variety и считаем среднее для каждой группы
iris.groupby('variety').mean()

,sepal.length,sepal.width,petal.length,petal.width
variety,,,,
Setosa,5.006,3.428,1.462,0.246
Versicolor,5.936,2.770,4.260,1.326
Virginica,6.588,2.974,5.552,2.026


Pandas разбил таблицу `iris` на три группы — по одной на каждый уникальный вид ириса. Для каждой группы вычислил среднее значение. В результате Pandas вернул DataFrame, где индекс содержит названия видов, а столбцы — средние значения признаков для каждого вида. 

**Чтобы посчитать максимум и минимум по группам, нужно использовать методы `.max()` и `.min()`, которые работают аналогично методу `.mean()`:**

In [129]:
# Группируем по variety и находим максимум в каждой группе
iris.groupby('variety').max()

,sepal.length,sepal.width,petal.length,petal.width
variety,,,,
Setosa,5.8,4.4,1.9,0.6
Versicolor,7.0,3.4,5.1,1.8
Virginica,7.9,3.8,6.9,2.5


In [130]:
# Группируем по variety и находим минимум в каждой группе
iris.groupby('variety').min()

,sepal.length,sepal.width,petal.length,petal.width
variety,,,,
Setosa,4.3,2.3,1.0,0.1
Versicolor,4.9,2.0,3.0,1.0
Virginica,4.9,2.2,4.5,1.4


Pandas вернул две таблицы: первая содержит максимальные значения для каждого признака внутри каждого вида, а вторая — минимальные. 

**Чтобы применить разные функции к разным столбцам, нужно использовать метод `.agg()`, который делает это через словарь:**

In [131]:
# Группируем по variety и применяем разные агрегаты
iris.groupby('variety').agg({

    # Считаем максимум и минимум
    'sepal.length': ['max', 'min'],

    # Считаем среднее и медиану
    'petal.length': ['mean', 'median'],

    # Считаем максимум
    'petal.width': 'max'
})

sepal.length      petal.length        petal.width
                    max  min         mean median         max
variety                                                     
Setosa              5.8  4.3        1.462   1.50         0.6
Versicolor          7.0  4.9        4.260   4.35         1.8
Virginica           7.9  4.9        5.552   5.55         2.5

Pandas вернул DataFrame с многоуровневым колоночным индексом: первый уровень — имена столбцов, второй уровень — имена функций. Для `sepal.length` видим два столбца, то есть `max` и `min`, для `petal.length` — два столбца, то есть `mean` и `median`, для `petal.width` — один столбец, то есть `max`.  

**Чтобы получить полную статистику по группам, нужно использовать метод `.describe()`, который вычисляет все основные статистики одновременно:**

In [134]:
# Группируем по variety и считаем статистику
iris.groupby('variety').describe()

sepal.length                                              \
                  count   mean       std  min    25%  50%  75%  max   
variety                                                               
Setosa             50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8   
Versicolor         50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0   
Virginica          50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9   

           sepal.width         ... petal.length      petal.width         \
                 count   mean  ...          75%  max       count   mean   
variety                        ...                                        
Setosa            50.0  3.428  ...        1.575  1.9        50.0  0.246   
Versicolor        50.0  2.770  ...        4.600  5.1        50.0  1.326   
Virginica         50.0  2.974  ...        5.875  6.9        50.0  2.026   

                                               
                 std  min  25%  50%  75%  max  
variety                                        
Setosa      0.105386  0.1  0.2  0.2  0.3  0.6  
Versicolor  0.197753  1.0  1.2  1.3  1.5  1.8  
Virginica   0.274650  1.4  1.8  2.0  2.3  2.5  

[3 rows x 32 columns]

**Pandas вернул DataFrame с трёхуровневой структурой столбцов:**
1. Первый уровень — исходные столбцы таблицы.
2. Второй уровень — статистики, например, `count`, `mean`, `std`, `min`, квартили, `max`.

Несмотря на то, что вывод громоздкий, он содержит полную информацию о распределении данных в каждой группе.

**Теперь рассмотрим объект GroupBy подробнее. Когда мы вызываем `.groupby()`, Pandas возвращает специальный объект DataFrameGroupBy:**

In [136]:
# Создаём объект группировки без агрегатов
iris.groupby('variety')

Pandas вернул объект, который ещё не содержит результат, но хранит информацию о том, как разбить данные на группы. Как только мы вызовём агрегирующий метод, например, `.mean()`, `.max()`, `.agg()`, Pandas выполнить вычисления и вернёт DataFrame с результатами.

**Чтобы применить собственную функцию к каждой группе, используем метод `.apply()`. Для `GroupBy` он работает аналогично DataFrame, но функция получает на вход целую подгрупп:**

In [142]:
# Определяем функцию для обработки одной группы
def my_function(gr):
    
    # Получаем название группы из атрибута name
    variety_name = gr.name
    
    # Проверяем вид через название группы
    if variety_name == 'Setosa':
        
        # Возводим ширину цветка в квадрат для Setosa
        gr['sepal.width'] = gr['sepal.width']**2
    
    # Проверяем, это группа Virginica или нет
    if variety_name == 'Virginica':
        
        # Возводим ширину цветка в куб для Virginica
        gr['sepal.width'] = gr['sepal.width']**3
    
    # Возвращаем изменённую группу
    return gr

# Применяем функцию к каждой группе
iris.groupby('variety', group_keys=False).apply(my_function)

,sepal.length,sepal.width,petal.length,petal.width
0,5.1,12.250,1.4,0.2
1,4.9,9.000,1.4,0.2
2,4.7,10.240,1.3,0.2
3,4.6,9.610,1.5,0.2
4,5.0,12.960,1.4,0.2
...,...,...,...,...
145,6.7,27.000,5.2,2.3
146,6.3,15.625,5.0,1.9
147,6.5,27.000,5.2,2.0
148,6.2,39.304,5.4,2.3


### Другие агрегирующие функции для группировки

Мы научились применять собственные функции к группам. Теперь разберёмся с дополнительными методами агрегации, которые работают внутри групп.

**Например, мы можем настроить ранжирование внутри групп с помощью метода `.rank()`, который присваиваем каждой строке порядковый номер внутри её группы на основе значений указанного столбца:**

In [147]:
# Присваиваем ранг по длине цветка внутри каждого вида
iris['sepal.length.rank'] = iris.groupby('variety')['sepal.length'].rank(method='dense')

# Выводим таблицу с новым столбцом
iris

,sepal.length,sepal.width,petal.length,petal.width,variety,sepal.length.rank
0,5.1,3.5,1.4,0.2,Setosa,9.0
1,4.9,3.0,1.4,0.2,Setosa,7.0
2,4.7,3.2,1.3,0.2,Setosa,5.0
3,4.6,3.1,1.5,0.2,Setosa,4.0
4,5.0,3.6,1.4,0.2,Setosa,8.0
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Virginica,12.0
146,6.3,2.5,5.0,1.9,Virginica,9.0
147,6.5,3.0,5.2,2.0,Virginica,11.0
148,6.2,3.4,5.4,2.3,Virginica,8.0


Pandas добавил столбец `sepal.length.rank`, который содержит ранг каждого цветка по длине цветка внутри своего вида. Параметр `method='dense'` означает, что одинаковые значения получают одинаковый ранг, а следующий ранг идёт без пропусков. Например, если три цветка имеют одинаковую минимальную длину, все три получат ранг `1`, а следующий цветок получит ранг `2`, а не `4`.

Это помогает отслеживать эволюцию параметров, например, можно присвоить номер события внутри группы и проследить, как меняются характеристики от события к событию.

### Мультииндекс

Когда мы групприуем таблицу по нескольким столбцам одновременно, Pandas создаёт многоуровневый индекс, то есть мультииндекс. Давайте разберёмся, как с ним работать.

**Для начала создадим таблицу с группировкой по двум столбцам:**

In [150]:
# Создаём DataFrame
df = pd.DataFrame ({

    # Первый столбец для группировки
    'A': ['foo', 'bar', 'foo', 'bar',
          'foo', 'bar', 'foo', 'foo'],

    # Второй столбец
    'B': ['one', 'one', 'two', 'three',
          'two', 'two', 'one', 'three'],

    # Случайные числа для первого значения
    'C': np.random.randn(8),

    # Случайные числа для второго значения
    'D': np.random.randn(8)
})

# Выгружаем исходную таблицу
df

,A,B,C,D
0,foo,one,0.117340,-0.367555
1,bar,one,1.255040,-0.500663
2,foo,two,1.028637,0.125618
3,bar,three,0.776008,-0.463751
4,foo,two,-0.182446,-2.157313
5,bar,two,-1.182553,-0.322659
6,foo,one,0.729950,0.149299
7,foo,three,-0.231642,-1.815112


**Теперь сгруппируем эту таблицу по двум столбцам:**

In [152]:
# Группируем значения по A и B, а затем считаем среднее
df.groupby(['A', 'B']).mean()

C         D
A   B                        
bar one    1.255040 -0.500663
    three  0.776008 -0.463751
    two   -1.182553 -0.322659
foo one    0.423645 -0.109128
    three -0.231642 -1.815112
    two    0.423096 -1.015848

**Pandas создал таблицу, где индекс состоит из двух уровней:**
1. **Первый уровень** — это значения столбца `A`, то есть `bar` и `foo`.
2. **Второй уровень** — это значения  столбца `B`, то есть `one`, `two` и `three`.

Каждая комбинация `(A, B)` образует одну строку результата.

**Давайте посмотрим на структуру индекса:**

In [155]:
# Смотрим на объект мультииндекса
df.groupby(['A', 'B']).mean().index

MultiIndex([('bar',   'one'),
            ('bar', 'three'),
            ('bar',   'two'),
            ('foo',   'one'),
            ('foo', 'three'),
            ('foo',   'two')],
           names=['A', 'B'])

Pandas вернул объект `MultiIndex` с двумя уровнями. Это специальный тип индекса, который хранит иерархическую структурую.

**Теперь сохраним результат для дальнейшей работы:**

In [158]:
# Сохраняем таблицу с мультииндексом
multi_gr = df.groupby(['A', 'B']).mean()

# Выводим таблицу
multi_gr

C         D
A   B                        
bar one    1.255040 -0.500663
    three  0.776008 -0.463751
    two   -1.182553 -0.322659
foo one    0.423645 -0.109128
    three -0.231642 -1.815112
    two    0.423096 -1.015848

**Для выборки по мультииндексу нужно передать кортеж значений, по одному для каждого уровня:**

In [161]:
# Выбираем строку с A=foo и B=three
multi_gr.loc[('foo', 'three')]

C   -0.231642
D   -1.815112
Name: (foo, three), dtype: float64

Pandas вернул Series со значения столбцов `C` и `D` для комбинации `('foo', 'three')`.

**Мы можем указать столбец во втором параметре:**

In [164]:
# Выбираем конкретное значение C для foo-three
multi_gr.loc[('foo', 'three'), 'C']

np.float64(-0.23164192875914127)

Pandas вернул одно число — это значение столбца `C` для строки `('foo', 'three')`.

Рассмотрим срезы по мультииндексы через `slice()`. Обычный синтаксис срезов через двоеточие не работает для кортежей. Например, выражение ('foo', 'one':'three') вызовет синтаксическую ошибку.

**Вместо этого мы будем использовать функцию `slice()`:**

In [165]:
# Берём срез от two к one с шагом -2
multi_gr.loc[('bar', slice('two', 'one', -2)), ['C', 'D']]

C         D
A   B                      
bar two -1.182553 -0.322659
    one  1.255040 -0.500663

Функция `slice(start, stop, step)` создаёт объект образа, аналогичный `start:stop:step`. Pandas выбрал строки с `A='bar'`, где второй уровень индекса идёт от `'two'` к `'one'` с шагом `-2`. Двоеточие в обычных срезах — это синтаксический сахар для вызова `slice()`. 

**Мы также можем использовать метод `.iloc[]`, чтобы работать с мультииндексом через позиции:**

In [167]:
# Берём строки с позиций 1 и 2
multi_gr.iloc[1:3]

C         D
A   B                        
bar three  0.776008 -0.463751
    two   -1.182553 -0.322659

Pandas вернул две строки независимо от структуры мультииндекса, то есть просто вторую и третью строки по порядку.

**Кроме того, мы можем распаковывать уровни индекса с помощью методов `.unstack()` и `.stack()`, чтобы преобразовывать уровни в столбцы и обратно:**

In [169]:
# Переносим уровень B из индекса в столбцы
multi_gr.unstack(level=1)

C                             D                    
B         one     three       two       one     three       two
A                                                              
bar  1.255040  0.776008 -1.182553 -0.500663 -0.463751 -0.322659
foo  0.423645 -0.231642  0.423096 -0.109128 -1.815112 -1.015848

Pandas создал таблицу, где значения `B`, то есть `one`, `two` и `three` стали частью колоночного индекса.

**Теперь колоночный индекс двухуровневый:**
1. **Первый уровень** — исходные столбцы `C` и `D`.
2. **Второй уровень** — значения `B`.

**Теперь распакуем нулевой уровень в столбце `A`:**

In [173]:
# Переносим уровень A из индекса в столбцы
multi_gr.unstack(level=0)

C                   D          
A           bar       foo       bar       foo
B                                            
one    1.255040  0.423645 -0.500663 -0.109128
three  0.776008 -0.231642 -0.463751 -1.815112
two   -1.182553  0.423096 -0.322659 -1.015848

Теперь значения `A`, то есть `bar` и `foo` стали часть колоночного индекса, а строковый индекс содержит только значения `B`.

**Упакуем столбцы обратно в индекс:**

In [176]:
# Распаковываем уровень 0, а затем упаковываем обратно
multi_gr.unstack(level=0).stack(level=0)

A             bar       foo
B                          
one   C  1.255040  0.423645
      D -0.500663 -0.109128
three C  0.776008 -0.231642
      D -0.463751 -1.815112
two   C -1.182553  0.423096
      D -0.322659 -1.015848

Метод `.stack()` переносит уровень из колоночного индекса в строковый. Мы вернули структуру к исходной.

**Теперь упакуем другой уровень:**

In [178]:
# Распаковываем уровень 0, упаковываем уровень 1
multi_gr.unstack(level=0).stack(level=1)

C         D
B     A                      
one   bar  1.255040 -0.500663
      foo  0.423645 -0.109128
three bar  0.776008 -0.463751
      foo -0.231642 -1.815112
two   bar -1.182553 -0.322659
      foo  0.423096 -1.015848

Результат отличается от исходной таблицы порядком уровней в индексе.

**Если мы вызоваем `.stack()` без параметров, то упакуем самый внутренний уровень колоночного индекса:**

In [180]:
multi_gr.stack()

A    B       
bar  one    C    1.255040
            D   -0.500663
     three  C    0.776008
            D   -0.463751
     two    C   -1.182553
            D   -0.322659
foo  one    C    0.423645
            D   -0.109128
     three  C   -0.231642
            D   -1.815112
     two    C    0.423096
            D   -1.015848
dtype: float64

Pandas перенёс названия столбцов `C` и `D` в индекс как третий уровень. Теперь индекс трёхуровневый, а таблица содержит только один столбец со значениями.

### Сводные таблицы

Мы научились работать с мультииндексом. Теперь разберёмся со сводными таблицами, которые помогают агрегировать данные. Сводная таблица похожа на `groupby`, но создаёт двумерную сетку вместо одномерного списка групп.

**Сводная таблица** — это объект, который принимает данные из отдельных столбцов, группирует их и формирует двумерную таблицу. Если `groupby` разделяется данные по одной оси, то есть по строкам, то сводная таблица разделяет данные по двум осям одновременно, то есть по строкам и столбцам. Данные разделяются, агрегируются и объединяются в двумерную сетку.

**Давайте создадим таблицу для демонстрации:**

In [183]:
# Создаём DataFrame
df = pd.DataFrame({

    # Повторяем категории три раза
    'Категория': ['Канцтовары', 'Одежда', 'Техника', 'Продукты'] * 3,

    # Повторяем города четыре раза
    'Город': ['Москва', 'Санкт-Петербург', 'Казань'] * 4,

    # Чередуем продавцов
    'Продавец': ['Андрей Субочев', 'Андрей Субочев', 'Андрей Субочев',
                 'Юрий Саночкин', 'Юрий Саночкин', 'Юрий Саночкин'] * 2,

    # Генерируем случайные значения выручки
    'Выручка': np.random.randint(0, 100, size=(12, )),

    # Генерируем случайные значения издержек
    'Издержки': np.random.randint(0, 100, size=(12,))
})

# Выводим таблицу
df

,Категория,Город,Продавец,Выручка,Издержки
0,Канцтовары,Москва,Андрей Субочев,66,98
1,Одежда,Санкт-Петербург,Андрей Субочев,58,89
2,Техника,Казань,Андрей Субочев,39,73
3,Продукты,Москва,Юрий Саночкин,99,9
4,Канцтовары,Санкт-Петербург,Юрий Саночкин,69,14
5,Одежда,Казань,Юрий Саночкин,57,68
6,Техника,Москва,Андрей Субочев,19,86
7,Продукты,Санкт-Петербург,Андрей Субочев,6,43
8,Канцтовары,Казань,Андрей Субочев,27,29
9,Одежда,Москва,Юрий Саночкин,84,87


Итоговая таблица содержит 12 строк — все комбинации категорий, городов и продавцов.

**Мы можем создать сводную таблицу с помощью функции `pd.pivot_table()`, которая принимает следующие ключевые параметры:**
- `values` — столбец со значениями, которые нужно агрегировать;
- `index` — столбец для строкового индекса, то есть группировка по строкам;
- `columns` — столбец для колоночного индекса, то есть группировка по столбцам;
- `aggfunc` — функция агрегации, то есть `sum`, `mean`, `count`, `max`, `min` и другие.

**Теперь создадим сводную таблицу, где строки — категории товаров, столбцы — продавцы, значения — сумма выручки:**

In [184]:
# Создаём сводную таблицу выручки
pd.pivot_table(df, values='Выручка', index='Категория', columns='Продавец', aggfunc='sum')

Продавец,Андрей Субочев,Юрий Саночкин
Категория,,
Канцтовары,93,69
Одежда,58,141
Продукты,6,145
Техника,58,96


Pandas создал таблицу, где каждая ячейка содержит сумму выручки для комбинации категории и продавца. Если для какой-то комбинации нет данных, Pandas заполняет ячейку `NaN`.

**Чтобы добавить строку и столбец с итогами по всем группам, нужно использовать параметр `marings=True`:**

In [186]:
# Добавляем итоги
pd.pivot_table(df, values='Выручка', index='Категория', columns='Продавец', aggfunc='sum', margins=True)

Продавец,Андрей Субочев,Юрий Саночкин,All
Категория,,,
Канцтовары,93,69,162
Одежда,58,141,199
Продукты,6,145,151
Техника,58,96,154
All,215,451,666


Pandas добавил столбец `All` справа, в котором находится сумма выручки по каждой категории для всех продавцов. Внизу появилась строка `All` — это сумма выручки по каждому продавцу для всех категорий. Ячейка в правом нижнем углу содержит общую сумму выручки по всей таблице. 

**Чтобы посчитать количество записей, нужно использовать функцию агрегации `count`, которая подсчитывает количество непустых значений:**

In [188]:
# Считаем количество записей
pd.pivot_table(df, values='Выручка', index='Категория', columns='Продавец', aggfunc='count')

Продавец,Андрей Субочев,Юрий Саночкин
Категория,,
Канцтовары,2,1
Одежда,1,2
Продукты,1,2
Техника,2,1


Pandas показал, сколько раз каждая комбинация категории и продавца встречается в данных. Это позволяет увидеть, где данных много, а где мало.

**Чтобы использовать разные функции для разных осей, нужно вычислить итоги вручную:**

In [190]:
# Создаём сводную с максимумами
pvt = pd.pivot_table(df, values='Выручка', index='Категория', columns='Продавец', aggfunc='max')

# Добавляем столбец со средним по строкам
pvt['All_mean'] = pvt.mean(axis=1)                                                                 

# Добавляем строку со средним по столбцам
pvt.loc['All_mean'] = pvt.mean(axis=0)

# Выводим таблицу с итогами
pvt                                                                                                 

Продавец,Андрей Субочев,Юрий Саночкин,All_mean
Категория,,,
Канцтовары,66.00,69.0,67.500
Одежда,58.00,84.0,71.000
Продукты,6.00,99.0,52.500
Техника,39.00,96.0,67.500
All_mean,42.25,87.0,64.625


Мы создали сводную таблицу с максимальными значениями выручки, затем добавили столбец `All_mean` со средним по каждой строке и строку `All_mean` со средним по каждому столбцу. Теперь внутри таблицы — максимумы, а в итогах — средние значения.

**В параметры `index` и `columns` можно передать список столбцов для создания многоуровневой группировки:**

In [191]:
# Группируем по категории и городу
pd.pivot_table(df, values='Выручка', index=['Категория', 'Город'], columns='Продавец', aggfunc='sum', margins=True)

Продавец                    Андрей Субочев  Юрий Саночкин  All
Категория  Город                                              
Канцтовары Казань                     27.0            NaN   27
           Москва                     66.0            NaN   66
           Санкт-Петербург             NaN           69.0   69
Одежда     Казань                      NaN           57.0   57
           Москва                      NaN           84.0   84
           Санкт-Петербург            58.0            NaN   58
Продукты   Казань                      NaN           46.0   46
           Москва                      NaN           99.0   99
           Санкт-Петербург             6.0            NaN    6
Техника    Казань                     39.0            NaN   39
           Москва                     19.0            NaN   19
           Санкт-Петербург             NaN           96.0   96
All                                  215.0          451.0  666

Pandas создал таблицу с двухуровневым строковым индексом: первый уровень — категория товара, второй уровень — город. Каждая ячейка содержит сумму выручки для комбинации категории, города и продавца. Итоги `All` считаются по всем уровням группировки.

**Функция `pd.crosstab()` работает аналогично `pivot_table`, но позволяет передавать столбцы напрямую, без указания исходного DataFrame:**

In [192]:
# Создаём сводную таблицу через crosstab
pd.crosstab(df['Категория'], df['Продавец'], values=df['Выручка'], aggfunc='max')

Продавец,Андрей Субочев,Юрий Саночкин
Категория,,
Канцтовары,66,69
Одежда,58,84
Продукты,6,99
Техника,39,96


Pandas создал сводную таблицу максимумов выручки. Разница с `pivot_table` в синтаксисе: `crosstab` принимает Series напрямую, а `pivot_table` принимает DataFrame и имена столбцов. Это удобно, когда нужно скомбинировать столбцы из разных таблиц.